RV32A_INST = [
    {'mnemonic': 'lr.w', 'handler': 'lr_w_32', 'cost': 1, 'tags': 'A_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'sc.w', 'handler': 'sc_w_32', 'cost': 1, 'tags': 'A_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amoswap.w', 'handler': 'amoswap_w_32', 'cost': 1, 'tags': 'A_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amoadd.w', 'handler': 'amoadd_w_32', 'cost': 1, 'tags': 'A_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amoxor.w', 'handler': 'amoxor_w_32', 'cost': 1, 'tags': 'A_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amoand.w', 'handler': 'amoand_w_32', 'cost': 1, 'tags': 'A_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amoor.w', 'handler': 'amoor_w_32', 'cost': 1, 'tags': 'A_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amomin.w', 'handler': 'amomin_w_32', 'cost': 1, 'tags': 'A_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amomax.w', 'handler': 'amomax_w_32', 'cost': 1, 'tags': 'A_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amominu.w', 'handler': 'amominu_w_32', 'cost': 1, 'tags': 'A_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amomaxu.w', 'handler': 'amomaxu_w_32', 'cost': 1, 'tags': 'A_EXT_32', 'memory': True, 'cof': False},
]

RV64A_INST = [
    {'mnemonic': 'lr.w', 'handler': 'lr_w_64', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'sc.w', 'handler': 'sc_w_64', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'lr.d', 'handler': 'lrd_64', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'sc.d', 'handler': 'scd_64', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoswap.w', 'handler': 'amoswap_w_64', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoadd.w', 'handler': 'amoadd_w_64', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoxor.w', 'handler': 'amoxor_w_64', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoand.w', 'handler': 'amoand_w_64', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoor.w', 'handler': 'amoor_w_64', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amomin.w', 'handler': 'amomin_w_64', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amomax.w', 'handler': 'amomax_w_64', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amominu.w', 'handler': 'amominu_w_64', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amomaxu.w', 'handler': 'amomaxu_w_64', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoswap.d', 'handler': 'amoswapd', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoadd.d', 'handler': 'amoaddd', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoxor.d', 'handler': 'amoxord', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoand.d', 'handler': 'amoandd', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoor.d', 'handler': 'amoord', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amomin.d', 'handler': 'amomind', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amomax.d', 'handler': 'amomaxd', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amominu.d', 'handler': 'amominud', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amomaxu.d', 'handler': 'amomaxud', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
]
