RVA_MAVIS_EXTS = ["a", "zalrsc", "zaamo"]

RV32A_INST = [
    {'mnemonic': 'lr.w', 'handler': 'lr_w', 'cost': 1, 'tags': 'A_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'sc.w', 'handler': 'sc_w', 'cost': 1, 'tags': 'A_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amoswap.w', 'handler': 'amoswap_w', 'cost': 1, 'tags': 'A_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amoadd.w', 'handler': 'amoadd_w', 'cost': 1, 'tags': 'A_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amoxor.w', 'handler': 'amoxor_w', 'cost': 1, 'tags': 'A_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amoand.w', 'handler': 'amoand_w', 'cost': 1, 'tags': 'A_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amoor.w', 'handler': 'amoor_w', 'cost': 1, 'tags': 'A_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amomin.w', 'handler': 'amomin_w', 'cost': 1, 'tags': 'A_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amomax.w', 'handler': 'amomax_w', 'cost': 1, 'tags': 'A_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amominu.w', 'handler': 'amominu_w', 'cost': 1, 'tags': 'A_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amomaxu.w', 'handler': 'amomaxu_w', 'cost': 1, 'tags': 'A_EXT_32', 'memory': True, 'cof': False},
]

RV64A_INST = [
    {'mnemonic': 'lr.w', 'handler': 'lr_w', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'sc.w', 'handler': 'sc_w', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'lr.d', 'handler': 'lr_d', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'sc.d', 'handler': 'sc_d', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoswap.w', 'handler': 'amoswap_w', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoadd.w', 'handler': 'amoadd_w', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoxor.w', 'handler': 'amoxor_w', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoand.w', 'handler': 'amoand_w', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoor.w', 'handler': 'amoor_w', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amomin.w', 'handler': 'amomin_w', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amomax.w', 'handler': 'amomax_w', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amominu.w', 'handler': 'amominu_w', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amomaxu.w', 'handler': 'amomaxu_w', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoswap.d', 'handler': 'amoswap_d', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoadd.d', 'handler': 'amoadd_d', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoxor.d', 'handler': 'amoxor_d', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoand.d', 'handler': 'amoand_d', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoor.d', 'handler': 'amoor_d', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amomin.d', 'handler': 'amomin_d', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amomax.d', 'handler': 'amomax_d', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amominu.d', 'handler': 'amominu_d', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amomaxu.d', 'handler': 'amomaxu_d', 'cost': 1, 'tags': 'A_EXT_64', 'memory': True, 'cof': False},
]
