RVD_MAVIS_EXTS = ["d", "zcd"]

RV32D_INST = [
    {'mnemonic': 'fmv.w.x', 'handler': 'fmv_w_x', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fmv.x.w', 'handler': 'fmv_x_w', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.d.w', 'handler': 'fcvt_d_w', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.d.wu', 'handler': 'fcvt_d_wu', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.w.d', 'handler': 'fcvt_w_d', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.wu.d', 'handler': 'fcvt_wu_d', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.d.s', 'handler': 'fcvt_d_s', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.s.d', 'handler': 'fcvt_s_d', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'flw', 'handler': 'flw', 'cost': 1, 'tags': 'D_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'fsw', 'handler': 'fsw', 'cost': 1, 'tags': 'D_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'fld', 'handler': 'fld', 'cost': 1, 'tags': 'D_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'fsd', 'handler': 'fsd', 'cost': 1, 'tags': 'D_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'fadd.d', 'handler': 'fadd_d', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fsub.d', 'handler': 'fsub_d', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fmul.d', 'handler': 'fmul_d', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fdiv.d', 'handler': 'fdiv_d', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fsqrt.d', 'handler': 'fsqrt_d', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fmadd.d', 'handler': 'fmadd_d', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fmsub.d', 'handler': 'fmsub_d', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fnmsub.d', 'handler': 'fnmsub_d', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fnmadd.d', 'handler': 'fnmadd_d', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fsgnj.d', 'handler': 'fsgnj_d', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fsgnjn.d', 'handler': 'fsgnjn_d', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fsgnjx.d', 'handler': 'fsgnjx_d', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fmin.d', 'handler': 'fmin_d', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fmax.d', 'handler': 'fmax_d', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'feq.d', 'handler': 'feq_d', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'flt.d', 'handler': 'flt_d', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fle.d', 'handler': 'fle_d', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fclass.d', 'handler': 'fclass_d', 'cost': 1, 'tags': 'D_EXT_32', 'memory': False, 'cof': False},
]

RV64D_INST = [
    {'mnemonic': 'fmv.w.x', 'handler': 'fmv_w_x', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fmv.x.w', 'handler': 'fmv_x_w', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fmv.x.d', 'handler': 'fmv_x_d', 'cost': 1, 'tags': 'D_EXT', 'memory': False, 'cof': False},
    {'mnemonic': 'fmv.d.x', 'handler': 'fmv_d_x', 'cost': 1, 'tags': 'D_EXT', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.d.w', 'handler': 'fcvt_d_w', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.d.wu', 'handler': 'fcvt_d_wu', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.w.d', 'handler': 'fcvt_w_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.wu.d', 'handler': 'fcvt_wu_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.l.d', 'handler': 'fcvt_l_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.lu.d', 'handler': 'fcvt_lu_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.d.l', 'handler': 'fcvt_d_l', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.d.lu', 'handler': 'fcvt_d_lu', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.d.s', 'handler': 'fcvt_d_s', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.s.d', 'handler': 'fcvt_s_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'flw', 'handler': 'flw', 'cost': 1, 'tags': 'D_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'fsw', 'handler': 'fsw', 'cost': 1, 'tags': 'D_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'fld', 'handler': 'fld', 'cost': 1, 'tags': 'D_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'fsd', 'handler': 'fsd', 'cost': 1, 'tags': 'D_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'fadd.d', 'handler': 'fadd_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fsub.d', 'handler': 'fsub_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fmul.d', 'handler': 'fmul_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fdiv.d', 'handler': 'fdiv_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fsqrt.d', 'handler': 'fsqrt_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fmadd.d', 'handler': 'fmadd_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fmsub.d', 'handler': 'fmsub_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fnmsub.d', 'handler': 'fnmsub_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fnmadd.d', 'handler': 'fnmadd_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fsgnj.d', 'handler': 'fsgnj_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fsgnjn.d', 'handler': 'fsgnjn_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fsgnjx.d', 'handler': 'fsgnjx_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fmin.d', 'handler': 'fmin_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fmax.d', 'handler': 'fmax_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'feq.d', 'handler': 'feq_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'flt.d', 'handler': 'flt_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fle.d', 'handler': 'fle_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fclass.d', 'handler': 'fclass_d', 'cost': 1, 'tags': 'D_EXT_64', 'memory': False, 'cof': False},
]
