RVF_MAVIS_EXTS = ["f", "zcf"]

RV32F_INST = [
    {'mnemonic': 'fmv.w.x', 'handler': 'fmv_w_x', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fmv.x.w', 'handler': 'fmv_x_w', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.s.w', 'handler': 'fcvt_s_w', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.s.wu', 'handler': 'fcvt_s_wu', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.w.s', 'handler': 'fcvt_w_s', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.wu.s', 'handler': 'fcvt_wu_s', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'flw', 'handler': 'flw', 'cost': 1, 'tags': 'F_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'fsw', 'handler': 'fsw', 'cost': 1, 'tags': 'F_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'fadd.s', 'handler': 'fadd_s', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fsub.s', 'handler': 'fsub_s', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fmul.s', 'handler': 'fmul_s', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fdiv.s', 'handler': 'fdiv_s', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fsqrt.s', 'handler': 'fsqrt_s', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fmadd.s', 'handler': 'fmadd_s', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fmsub.s', 'handler': 'fmsub_s', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fnmsub.s', 'handler': 'fnmsub_s', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fnmadd.s', 'handler': 'fnmadd_s', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fsgnj.s', 'handler': 'fsgnj_s', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fsgnjn.s', 'handler': 'fsgnjn_s', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fsgnjx.s', 'handler': 'fsgnjx_s', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fmin.s', 'handler': 'fmin_s', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fmax.s', 'handler': 'fmax_s', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'feq.s', 'handler': 'feq_s', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'flt.s', 'handler': 'flt_s', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fle.s', 'handler': 'fle_s', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fclass.s', 'handler': 'fclass_s', 'cost': 1, 'tags': 'F_EXT_32', 'memory': False, 'cof': False},
]

RV64F_INST = [
    {'mnemonic': 'fmv.w.x', 'handler': 'fmv_w_x', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fmv.x.w', 'handler': 'fmv_x_w', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.s.w', 'handler': 'fcvt_s_w', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.s.wu', 'handler': 'fcvt_s_wu', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.w.s', 'handler': 'fcvt_w_s', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.wu.s', 'handler': 'fcvt_wu_s', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.l.s', 'handler': 'fcvt_l_s', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.lu.s', 'handler': 'fcvt_lu_s', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.s.l', 'handler': 'fcvt_s_l', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.s.lu', 'handler': 'fcvt_s_lu', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'flw', 'handler': 'flw', 'cost': 1, 'tags': 'F_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'fsw', 'handler': 'fsw', 'cost': 1, 'tags': 'F_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'fadd.s', 'handler': 'fadd_s', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fsub.s', 'handler': 'fsub_s', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fmul.s', 'handler': 'fmul_s', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fdiv.s', 'handler': 'fdiv_s', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fsqrt.s', 'handler': 'fsqrt_s', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fmadd.s', 'handler': 'fmadd_s', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fmsub.s', 'handler': 'fmsub_s', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fnmsub.s', 'handler': 'fnmsub_s', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fnmadd.s', 'handler': 'fnmadd_s', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fsgnj.s', 'handler': 'fsgnj_s', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fsgnjn.s', 'handler': 'fsgnjn_s', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fsgnjx.s', 'handler': 'fsgnjx_s', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fmin.s', 'handler': 'fmin_s', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fmax.s', 'handler': 'fmax_s', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'feq.s', 'handler': 'feq_s', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'flt.s', 'handler': 'flt_s', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fle.s', 'handler': 'fle_s', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fclass.s', 'handler': 'fclass_s', 'cost': 1, 'tags': 'F_EXT_64', 'memory': False, 'cof': False},
]
