RVV_MAVIS_EXTS = ["v", "zve32x", "zve32f", "zve64f", "zve64d", "zve64x"]

RVZVE32X_INST = [
    {'mnemonic': 'vsetvli', 'handler': 'vsetvli', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsetvl', 'handler': 'vsetvl', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsetivli', 'handler': 'vsetivli', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vle8.v', 'handler': 'vle8.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew8']},
    {'mnemonic': 'vle16.v', 'handler': 'vle16.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew16']},
    {'mnemonic': 'vle32.v', 'handler': 'vle32.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew32']},
    {'mnemonic': 'vlm.v', 'handler': 'vlm.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False},
    {'mnemonic': 'vsm.v', 'handler': 'vsm.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False},
    {'mnemonic': 'vse8.v', 'handler': 'vse8.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew8']},
    {'mnemonic': 'vse16.v', 'handler': 'vse16.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew16']},
    {'mnemonic': 'vse32.v', 'handler': 'vse32.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew32']},
    {'mnemonic': 'vlse8.v', 'handler': 'vlse8.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew8']},
    {'mnemonic': 'vlse16.v', 'handler': 'vlse16.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew16']},
    {'mnemonic': 'vlse32.v', 'handler': 'vlse32.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew32']},
    {'mnemonic': 'vsse8.v', 'handler': 'vsse8.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew8']},
    {'mnemonic': 'vsse16.v', 'handler': 'vsse16.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew16']},
    {'mnemonic': 'vsse32.v', 'handler': 'vsse32.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew32']},
    {'mnemonic': 'vloxei8.v', 'handler': 'vloxei8.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False},
    {'mnemonic': 'vloxei16.v', 'handler': 'vloxei16.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False},
    {'mnemonic': 'vloxei32.v', 'handler': 'vloxei32.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False},
    {'mnemonic': 'vluxei8.v', 'handler': 'vluxei8.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False},
    {'mnemonic': 'vluxei16.v', 'handler': 'vluxei16.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False},
    {'mnemonic': 'vluxei32.v', 'handler': 'vluxei32.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False},
    {'mnemonic': 'vsoxei8.v', 'handler': 'vsoxei8.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False},
    {'mnemonic': 'vsoxei16.v', 'handler': 'vsoxei16.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False},
    {'mnemonic': 'vsoxei32.v', 'handler': 'vsoxei32.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False},
    {'mnemonic': 'vsuxei8.v', 'handler': 'vsuxei8.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False},
    {'mnemonic': 'vsuxei16.v', 'handler': 'vsuxei16.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False},
    {'mnemonic': 'vsuxei32.v', 'handler': 'vsuxei32.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False},
    {'mnemonic': 'vle8ff.v', 'handler': 'vle8ff.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew8']},
    {'mnemonic': 'vle16ff.v', 'handler': 'vle16ff.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew16']},
    {'mnemonic': 'vle32ff.v', 'handler': 'vle32ff.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew32']},
    {'mnemonic': 'vl1re8.v', 'handler': 'vl1re8.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew8', 'emul1', 'vlmax']},
    {'mnemonic': 'vl1re16.v', 'handler': 'vl1re16.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew16', 'emul1', 'vlmax']},
    {'mnemonic': 'vl1re32.v', 'handler': 'vl1re32.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew32', 'emul1', 'vlmax']},
    {'mnemonic': 'vl2re8.v', 'handler': 'vl2re8.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew8', 'emul2', 'vlmax']},
    {'mnemonic': 'vl2re16.v', 'handler': 'vl2re16.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew16', 'emul2', 'vlmax']},
    {'mnemonic': 'vl2re32.v', 'handler': 'vl2re32.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew32', 'emul2', 'vlmax']},
    {'mnemonic': 'vl4re8.v', 'handler': 'vl4re8.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew8', 'emul4', 'vlmax']},
    {'mnemonic': 'vl4re16.v', 'handler': 'vl4re16.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew16', 'emul4', 'vlmax']},
    {'mnemonic': 'vl4re32.v', 'handler': 'vl4re32.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew32', 'emul4', 'vlmax']},
    {'mnemonic': 'vl8re8.v', 'handler': 'vl8re8.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew8', 'emul8', 'vlmax']},
    {'mnemonic': 'vl8re16.v', 'handler': 'vl8re16.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew16', 'emul8', 'vlmax']},
    {'mnemonic': 'vl8re32.v', 'handler': 'vl8re32.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew32', 'emul8', 'vlmax']},
    {'mnemonic': 'vs1r.v', 'handler': 'vs1r.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew32', 'emul1', 'vlmax']},
    {'mnemonic': 'vs2r.v', 'handler': 'vs2r.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew32', 'emul2', 'vlmax']},
    {'mnemonic': 'vs4r.v', 'handler': 'vs4r.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew32', 'emul4', 'vlmax']},
    {'mnemonic': 'vs8r.v', 'handler': 'vs8r.v', 'cost': 1, 'tags': '.json', 'memory': True, 'cof': False, 'veccfg': ['eew32', 'emul8', 'vlmax']},
    {'mnemonic': 'vadd.vx', 'handler': 'vadd.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsub.vx', 'handler': 'vsub.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vrsub.vx', 'handler': 'vrsub.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vminu.vx', 'handler': 'vminu.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmin.vx', 'handler': 'vmin.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmaxu.vx', 'handler': 'vmaxu.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmax.vx', 'handler': 'vmax.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vand.vx', 'handler': 'vand.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vor.vx', 'handler': 'vor.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vxor.vx', 'handler': 'vxor.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vrgather.vx', 'handler': 'vrgather.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vslideup.vx', 'handler': 'vslideup.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vslidedown.vx', 'handler': 'vslidedown.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vadc.vxm', 'handler': 'vadc.vxm', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmadc.vxm', 'handler': 'vmadc.vxm', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsbc.vxm', 'handler': 'vsbc.vxm', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmsbc.vxm', 'handler': 'vmsbc.vxm', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmerge.vxm', 'handler': 'vmerge.vxm', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmv.v.x', 'handler': 'vmv.v.x', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmseq.vx', 'handler': 'vmseq.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmsne.vx', 'handler': 'vmsne.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmsltu.vx', 'handler': 'vmsltu.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmslt.vx', 'handler': 'vmslt.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmsleu.vx', 'handler': 'vmsleu.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmsle.vx', 'handler': 'vmsle.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmsgtu.vx', 'handler': 'vmsgtu.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmsgt.vx', 'handler': 'vmsgt.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsaddu.vx', 'handler': 'vsaddu.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsadd.vx', 'handler': 'vsadd.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vssubu.vx', 'handler': 'vssubu.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vssub.vx', 'handler': 'vssub.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsll.vx', 'handler': 'vsll.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsmul.vx', 'handler': 'vsmul.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsrl.vx', 'handler': 'vsrl.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsra.vx', 'handler': 'vsra.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vssrl.vx', 'handler': 'vssrl.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vssra.vx', 'handler': 'vssra.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vnsrl.wx', 'handler': 'vnsrl.wx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vnsra.wx', 'handler': 'vnsra.wx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vnclipu.wx', 'handler': 'vnclipu.wx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vnclip.wx', 'handler': 'vnclip.wx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vadd.vv', 'handler': 'vadd.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsub.vv', 'handler': 'vsub.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vminu.vv', 'handler': 'vminu.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmin.vv', 'handler': 'vmin.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmaxu.vv', 'handler': 'vmaxu.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmax.vv', 'handler': 'vmax.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vand.vv', 'handler': 'vand.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vor.vv', 'handler': 'vor.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vxor.vv', 'handler': 'vxor.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vrgather.vv', 'handler': 'vrgather.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vrgatherei16.vv', 'handler': 'vrgatherei16.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vadc.vvm', 'handler': 'vadc.vvm', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmadc.vvm', 'handler': 'vmadc.vvm', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsbc.vvm', 'handler': 'vsbc.vvm', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmsbc.vvm', 'handler': 'vmsbc.vvm', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmerge.vvm', 'handler': 'vmerge.vvm', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmv.v.v', 'handler': 'vmv.v.v', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmseq.vv', 'handler': 'vmseq.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmsne.vv', 'handler': 'vmsne.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmsltu.vv', 'handler': 'vmsltu.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmslt.vv', 'handler': 'vmslt.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmsleu.vv', 'handler': 'vmsleu.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmsle.vv', 'handler': 'vmsle.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsaddu.vv', 'handler': 'vsaddu.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsadd.vv', 'handler': 'vsadd.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vssubu.vv', 'handler': 'vssubu.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vssub.vv', 'handler': 'vssub.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsll.vv', 'handler': 'vsll.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsmul.vv', 'handler': 'vsmul.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsrl.vv', 'handler': 'vsrl.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsra.vv', 'handler': 'vsra.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vssrl.vv', 'handler': 'vssrl.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vssra.vv', 'handler': 'vssra.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vnsrl.wv', 'handler': 'vnsrl.wv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vnsra.wv', 'handler': 'vnsra.wv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vnclipu.wv', 'handler': 'vnclipu.wv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vnclip.wv', 'handler': 'vnclip.wv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwredsumu.vs', 'handler': 'vwredsumu.vs', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwredsum.vs', 'handler': 'vwredsum.vs', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vadd.vi', 'handler': 'vadd.vi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vrsub.vi', 'handler': 'vrsub.vi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vand.vi', 'handler': 'vand.vi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vor.vi', 'handler': 'vor.vi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vxor.vi', 'handler': 'vxor.vi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vrgather.vi', 'handler': 'vrgather.vi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vslideup.vi', 'handler': 'vslideup.vi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vslidedown.vi', 'handler': 'vslidedown.vi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vadc.vim', 'handler': 'vadc.vim', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmadc.vim', 'handler': 'vmadc.vim', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmerge.vim', 'handler': 'vmerge.vim', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmv.v.i', 'handler': 'vmv.v.i', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmseq.vi', 'handler': 'vmseq.vi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmsne.vi', 'handler': 'vmsne.vi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmsleu.vi', 'handler': 'vmsleu.vi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmsle.vi', 'handler': 'vmsle.vi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmsgtu.vi', 'handler': 'vmsgtu.vi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmsgt.vi', 'handler': 'vmsgt.vi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsaddu.vi', 'handler': 'vsaddu.vi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsadd.vi', 'handler': 'vsadd.vi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsll.vi', 'handler': 'vsll.vi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmv1r.v', 'handler': 'vmv1r.v', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False, 'veccfg': ['emul1', 'vlmax']},
    {'mnemonic': 'vmv2r.v', 'handler': 'vmv2r.v', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False, 'veccfg': ['emul2', 'vlmax']},
    {'mnemonic': 'vmv4r.v', 'handler': 'vmv4r.v', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False, 'veccfg': ['emul4', 'vlmax']},
    {'mnemonic': 'vmv8r.v', 'handler': 'vmv8r.v', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False, 'veccfg': ['emul8', 'vlmax']},
    {'mnemonic': 'vsrl.vi', 'handler': 'vsrl.vi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsra.vi', 'handler': 'vsra.vi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vssrl.vi', 'handler': 'vssrl.vi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vssra.vi', 'handler': 'vssra.vi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vnsrl.wi', 'handler': 'vnsrl.wi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vnsra.wi', 'handler': 'vnsra.wi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vnclipu.wi', 'handler': 'vnclipu.wi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vnclip.wi', 'handler': 'vnclip.wi', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vredsum.vs', 'handler': 'vredsum.vs', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vredand.vs', 'handler': 'vredand.vs', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vredor.vs', 'handler': 'vredor.vs', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vredxor.vs', 'handler': 'vredxor.vs', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vredminu.vs', 'handler': 'vredminu.vs', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vredmin.vs', 'handler': 'vredmin.vs', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vredmaxu.vs', 'handler': 'vredmaxu.vs', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vredmax.vs', 'handler': 'vredmax.vs', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vaaddu.vv', 'handler': 'vaaddu.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vaadd.vv', 'handler': 'vaadd.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vasubu.vv', 'handler': 'vasubu.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vasub.vv', 'handler': 'vasub.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmv.x.s', 'handler': 'vmv.x.s', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vzext.vf8', 'handler': 'vzext.vf8', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsext.vf8', 'handler': 'vsext.vf8', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vzext.vf4', 'handler': 'vzext.vf4', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsext.vf4', 'handler': 'vsext.vf4', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vzext.vf2', 'handler': 'vzext.vf2', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vsext.vf2', 'handler': 'vsext.vf2', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vcompress.vm', 'handler': 'vcompress.vm', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmandn.mm', 'handler': 'vmandn.mm', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmand.mm', 'handler': 'vmand.mm', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmor.mm', 'handler': 'vmor.mm', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmxor.mm', 'handler': 'vmxor.mm', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmorn.mm', 'handler': 'vmorn.mm', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmnand.mm', 'handler': 'vmnand.mm', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmnor.mm', 'handler': 'vmnor.mm', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmxnor.mm', 'handler': 'vmxnor.mm', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmsbf.m', 'handler': 'vmsbf.m', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmsof.m', 'handler': 'vmsof.m', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmsif.m', 'handler': 'vmsif.m', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'viota.m', 'handler': 'viota.m', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vid.v', 'handler': 'vid.v', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vcpop.m', 'handler': 'vcpop.m', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfirst.m', 'handler': 'vfirst.m', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vdivu.vv', 'handler': 'vdivu.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vdiv.vv', 'handler': 'vdiv.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vremu.vv', 'handler': 'vremu.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vrem.vv', 'handler': 'vrem.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmulhu.vv', 'handler': 'vmulhu.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmul.vv', 'handler': 'vmul.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmulhsu.vv', 'handler': 'vmulhsu.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmulh.vv', 'handler': 'vmulh.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmadd.vv', 'handler': 'vmadd.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vnmsub.vv', 'handler': 'vnmsub.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmacc.vv', 'handler': 'vmacc.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vnmsac.vv', 'handler': 'vnmsac.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwaddu.vv', 'handler': 'vwaddu.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwadd.vv', 'handler': 'vwadd.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwsubu.vv', 'handler': 'vwsubu.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwsub.vv', 'handler': 'vwsub.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwaddu.wv', 'handler': 'vwaddu.wv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwadd.wv', 'handler': 'vwadd.wv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwsubu.wv', 'handler': 'vwsubu.wv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwsub.wv', 'handler': 'vwsub.wv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwmulu.vv', 'handler': 'vwmulu.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwmulsu.vv', 'handler': 'vwmulsu.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwmul.vv', 'handler': 'vwmul.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwmaccu.vv', 'handler': 'vwmaccu.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwmacc.vv', 'handler': 'vwmacc.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwmaccsu.vv', 'handler': 'vwmaccsu.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vaaddu.vx', 'handler': 'vaaddu.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vaadd.vx', 'handler': 'vaadd.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vasubu.vx', 'handler': 'vasubu.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vasub.vx', 'handler': 'vasub.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmv.s.x', 'handler': 'vmv.s.x', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vslide1up.vx', 'handler': 'vslide1up.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vslide1down.vx', 'handler': 'vslide1down.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vdivu.vx', 'handler': 'vdivu.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vdiv.vx', 'handler': 'vdiv.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vremu.vx', 'handler': 'vremu.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vrem.vx', 'handler': 'vrem.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmulhu.vx', 'handler': 'vmulhu.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmul.vx', 'handler': 'vmul.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmulhsu.vx', 'handler': 'vmulhsu.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmulh.vx', 'handler': 'vmulh.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmadd.vx', 'handler': 'vmadd.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vnmsub.vx', 'handler': 'vnmsub.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmacc.vx', 'handler': 'vmacc.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vnmsac.vx', 'handler': 'vnmsac.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwaddu.vx', 'handler': 'vwaddu.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwadd.vx', 'handler': 'vwadd.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwsubu.vx', 'handler': 'vwsubu.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwsub.vx', 'handler': 'vwsub.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwaddu.wx', 'handler': 'vwaddu.wx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwadd.wx', 'handler': 'vwadd.wx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwsubu.wx', 'handler': 'vwsubu.wx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwsub.wx', 'handler': 'vwsub.wx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwmulu.vx', 'handler': 'vwmulu.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwmulsu.vx', 'handler': 'vwmulsu.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwmul.vx', 'handler': 'vwmul.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwmaccu.vx', 'handler': 'vwmaccu.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwmacc.vx', 'handler': 'vwmacc.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwmaccus.vx', 'handler': 'vwmaccus.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vwmaccsu.vx', 'handler': 'vwmaccsu.vx', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
]

RVZVE32F_INST = [
    {'mnemonic': 'vfadd.vf', 'handler': 'vfadd.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfsub.vf', 'handler': 'vfsub.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfmin.vf', 'handler': 'vfmin.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfmax.vf', 'handler': 'vfmax.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfsgnj.vf', 'handler': 'vfsgnj.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfsgnjn.vf', 'handler': 'vfsgnjn.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfsgnjx.vf', 'handler': 'vfsgnjx.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfslide1up.vf', 'handler': 'vfslide1up.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfslide1down.vf', 'handler': 'vfslide1down.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfmv.s.f', 'handler': 'vfmv.s.f', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfmerge.vfm', 'handler': 'vfmerge.vfm', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfmv.v.f', 'handler': 'vfmv.v.f', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmfeq.vf', 'handler': 'vmfeq.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmfle.vf', 'handler': 'vmfle.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmflt.vf', 'handler': 'vmflt.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmfne.vf', 'handler': 'vmfne.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmfgt.vf', 'handler': 'vmfgt.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmfge.vf', 'handler': 'vmfge.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfdiv.vf', 'handler': 'vfdiv.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfrdiv.vf', 'handler': 'vfrdiv.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfmul.vf', 'handler': 'vfmul.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfrsub.vf', 'handler': 'vfrsub.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfmadd.vf', 'handler': 'vfmadd.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfnmadd.vf', 'handler': 'vfnmadd.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfmsub.vf', 'handler': 'vfmsub.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfnmsub.vf', 'handler': 'vfnmsub.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfmacc.vf', 'handler': 'vfmacc.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfnmacc.vf', 'handler': 'vfnmacc.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfmsac.vf', 'handler': 'vfmsac.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfnmsac.vf', 'handler': 'vfnmsac.vf', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfadd.vv', 'handler': 'vfadd.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfredusum.vs', 'handler': 'vfredosum.vs', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfsub.vv', 'handler': 'vfsub.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfredosum.vs', 'handler': 'vfredosum.vs', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfmin.vv', 'handler': 'vfmin.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfredmin.vs', 'handler': 'vfredmin.vs', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfmax.vv', 'handler': 'vfmax.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfredmax.vs', 'handler': 'vfredmax.vs', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfsgnj.vv', 'handler': 'vfsgnj.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfsgnjn.vv', 'handler': 'vfsgnjn.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfsgnjx.vv', 'handler': 'vfsgnjx.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfmv.f.s', 'handler': 'vfmv.f.s', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmfeq.vv', 'handler': 'vmfeq.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmfle.vv', 'handler': 'vmfle.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmflt.vv', 'handler': 'vmflt.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vmfne.vv', 'handler': 'vmfne.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfdiv.vv', 'handler': 'vfdiv.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfmul.vv', 'handler': 'vfmul.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfmadd.vv', 'handler': 'vfmadd.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfnmadd.vv', 'handler': 'vfnmadd.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfmsub.vv', 'handler': 'vfmsub.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfnmsub.vv', 'handler': 'vfnmsub.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfmacc.vv', 'handler': 'vfmacc.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfnmacc.vv', 'handler': 'vfnmacc.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfmsac.vv', 'handler': 'vfmsac.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfnmsac.vv', 'handler': 'vfnmsac.vv', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfcvt.xu.f.v', 'handler': 'vfcvt.xu.f.v', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfcvt.x.f.v', 'handler': 'vfcvt.x.f.v', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfcvt.f.xu.v', 'handler': 'vfcvt.f.xu.v', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfcvt.f.x.v', 'handler': 'vfcvt.f.x.v', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfcvt.rtz.xu.f.v', 'handler': 'vfcvt.rtz.xu.f.v', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfcvt.rtz.x.f.v', 'handler': 'vfcvt.rtz.x.f.v', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfncvt.xu.f.w', 'handler': 'vfncvt.xu.f.w', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfncvt.x.f.w', 'handler': 'vfncvt.x.f.w', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfncvt.f.xu.w', 'handler': 'vfncvt.f.xu.w', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfncvt.f.x.w', 'handler': 'vfncvt.f.x.w', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfncvt.f.f.w', 'handler': 'vfncvt.f.f.w', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfncvt.rod.f.f.w', 'handler': 'vfncvt.rod.f.f.w', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfncvt.rtz.xu.f.w', 'handler': 'vfncvt.rtz.xu.f.w', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfncvt.rtz.x.f.w', 'handler': 'vfncvt.rtz.x.f.w', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfsqrt.v', 'handler': 'vfsqrt.v', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfrsqrt7.v', 'handler': 'vfrsqrt7.v', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfrec7.v', 'handler': 'vfrec7.v', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False},
    {'mnemonic': 'vfclass.v', 'handler': 'vfclass.v', 'cost': 1, 'tags': '.json', 'memory': False, 'cof': False}
]

RVZVE64D_INST = [
    {'mnemonic': 'vfwadd.vf', 'handler': 'vfwadd.vf', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwsub.vf', 'handler': 'vfwsub.vf', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwadd.wf', 'handler': 'vfwadd.wf', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwsub.wf', 'handler': 'vfwsub.wf', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwmul.vf', 'handler': 'vfwmul.vf', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwmacc.vf', 'handler': 'vfwmacc.vf', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwnmacc.vf', 'handler': 'vfwnmacc.vf', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwmsac.vf', 'handler': 'vfwmsac.vf', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwnmsac.vf', 'handler': 'vfwnmsac.vf', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwcvt.xu.f.v', 'handler': 'vfwcvt.xu.f.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwcvt.x.f.v', 'handler': 'vfwcvt.x.f.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwcvt.f.xu.v', 'handler': 'vfwcvt.f.xu.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwcvt.f.x.v', 'handler': 'vfwcvt.f.x.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwcvt.f.f.v', 'handler': 'vfwcvt.f.f.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwcvt.rtz.xu.f.v', 'handler': 'vfwcvt.rtz.xu.f.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwcvt.rtz.x.f.v', 'handler': 'vfwcvt.rtz.x.f.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwadd.vv', 'handler': 'vfwadd.vv', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwredusum.vs', 'handler': 'vfwredusum.vs', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwsub.vv', 'handler': 'vfwsub.vv', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwredosum.vs', 'handler': 'vfwredosum.vs', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwadd.wv', 'handler': 'vfwadd.wv', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwsub.wv', 'handler': 'vfwsub.wv', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwmul.vv', 'handler': 'vfwmul.vv', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwmacc.vv', 'handler': 'vfwmacc.vv', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwnmacc.vv', 'handler': 'vfwnmacc.vv', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwmsac.vv', 'handler': 'vfwmsac.vv', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'vfwnmsac.vv', 'handler': 'vfwnmsac.vv', 'cost': 1, 'tags': 'V_EXT_64', 'memory': False, 'cof': False},
]

RVZVE64X_INST = [
    {'mnemonic': 'vle64.v', 'handler': 'vle64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False, 'veccfg': ['eew64']},
    {'mnemonic': 'vse64.v', 'handler': 'vse64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False, 'veccfg': ['eew64']},
    {'mnemonic': 'vlse64.v', 'handler': 'vlse64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False, 'veccfg': ['eew64']},
    {'mnemonic': 'vsse64.v', 'handler': 'vsse64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False, 'veccfg': ['eew64']},
    {'mnemonic': 'vloxei64.v', 'handler': 'vloxei64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'vluxei64.v', 'handler': 'vluxei64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'vsoxei64.v', 'handler': 'vsoxei64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'vsuxei64.v', 'handler': 'vsuxei64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'vle64ff.v', 'handler': 'vle64ff.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False, 'veccfg': ['eew64']},
    {'mnemonic': 'vl1re64.v', 'handler': 'vl1re64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False, 'veccfg': ['eew64', 'emul1', 'vlmax']},
    {'mnemonic': 'vl2re64.v', 'handler': 'vl2re64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False, 'veccfg': ['eew64', 'emul2', 'vlmax']},
    {'mnemonic': 'vl4re64.v', 'handler': 'vl4re64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False, 'veccfg': ['eew64', 'emul4', 'vlmax']},
    {'mnemonic': 'vl8re64.v', 'handler': 'vl8re64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False, 'veccfg': ['eew64', 'emul8', 'vlmax']},
]
