RVZABHA_MAVIS_EXTS = ["zabha"]

RV32ZABHA_INST = [
    {'mnemonic': 'lr.b', 'handler': 'lr_b', 'cost': 1, 'tags': 'ZABHA_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'sc.b', 'handler': 'sc_b', 'cost': 1, 'tags': 'ZABHA_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'lr.h', 'handler': 'lr_h', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'sc.h', 'handler': 'sc_h', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoswap.b', 'handler': 'amoswap_b', 'cost': 1, 'tags': 'ZABHA_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amoadd.b', 'handler': 'amoadd_b', 'cost': 1, 'tags': 'ZABHA_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amoxor.b', 'handler': 'amoxor_b', 'cost': 1, 'tags': 'ZABHA_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amoand.b', 'handler': 'amoand_b', 'cost': 1, 'tags': 'ZABHA_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amoor.b', 'handler': 'amoor_b', 'cost': 1, 'tags': 'ZABHA_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amomin.b', 'handler': 'amomin_b', 'cost': 1, 'tags': 'ZABHA_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amomax.b', 'handler': 'amomax_b', 'cost': 1, 'tags': 'ZABHA_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amominu.b', 'handler': 'amominu_b', 'cost': 1, 'tags': 'ZABHA_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amomaxu.b', 'handler': 'amomaxu_b', 'cost': 1, 'tags': 'ZABHA_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'amoswap.h', 'handler': 'amoswap_h', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoadd.h', 'handler': 'amoadd_h', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoxor.h', 'handler': 'amoxor_h', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoand.h', 'handler': 'amoand_h', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoor.h', 'handler': 'amoor_h', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amomin.h', 'handler': 'amomin_h', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amomax.h', 'handler': 'amomax_h', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amominu.h', 'handler': 'amominu_h', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amomaxu.h', 'handler': 'amomaxu_h', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
]

RV64ZABHA_INST = [
    {'mnemonic': 'lr.b', 'handler': 'lr_b', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'sc.b', 'handler': 'sc_b', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'lr.h', 'handler': 'lr_h', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'sc.h', 'handler': 'sc_h', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoswap.b', 'handler': 'amoswap_b', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoadd.b', 'handler': 'amoadd_b', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoxor.b', 'handler': 'amoxor_b', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoand.b', 'handler': 'amoand_b', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoor.b', 'handler': 'amoor_b', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amomin.b', 'handler': 'amomin_b', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amomax.b', 'handler': 'amomax_b', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amominu.b', 'handler': 'amominu_b', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amomaxu.b', 'handler': 'amomaxu_b', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoswap.h', 'handler': 'amoswap_h', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoadd.h', 'handler': 'amoadd_h', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoxor.h', 'handler': 'amoxor_h', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoand.h', 'handler': 'amoand_h', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amoor.h', 'handler': 'amoor_h', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amomin.h', 'handler': 'amomin_h', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amomax.h', 'handler': 'amomax_h', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amominu.h', 'handler': 'amominu_h', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'amomaxu.h', 'handler': 'amomaxu_h', 'cost': 1, 'tags': 'ZABHA_EXT_64', 'memory': True, 'cof': False},
]
