RVZFA_MAVIS_EXTS = ["zfa"]

RV32ZFA_INST = [
    {'mnemonic': 'fleq.s', 'handler': 'fleq.s', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fli.s', 'handler': 'fli.s', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fltq.s', 'handler': 'fltq.s', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fmaxm.s', 'handler': 'fmaxm.s', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fminm.s', 'handler': 'fminm.s', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fround.s', 'handler': 'fround.s', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'froundnx.s', 'handler': 'froundnx.s', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvtmod.w.d', 'handler': 'fcvtmod.w.d', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fleq.d', 'handler': 'fleq.d', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fli.d', 'handler': 'fli.d', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fltq.d', 'handler': 'fltq.d', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fmaxm.d', 'handler': 'fmaxm.d', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fminm.d', 'handler': 'fminm.d', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fround.d', 'handler': 'fround.d', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'froundnx.d', 'handler': 'froundnx.d', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fmvh.x.d', 'handler': 'fmvh.x.d', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fmvp.d.x', 'handler': 'fmvp.d.x', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    #{'mnemonic': 'fleq.h', 'handler': 'fleq.h', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    #{'mnemonic': 'fli.h', 'handler': 'fli.h', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    #{'mnemonic': 'fltq.h', 'handler': 'fltq.h', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    #{'mnemonic': 'fmaxm.h', 'handler': 'fmaxm.h', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    #{'mnemonic': 'fminm.h', 'handler': 'fminm.h', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    #{'mnemonic': 'fround.h', 'handler': 'fround.h', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
    #{'mnemonic': 'froundnx.h', 'handler': 'froundnx.h', 'cost': 1, 'tags': 'ZFA_EXT_32', 'memory': False, 'cof': False},
]

RV64ZFA_INST = [
    {'mnemonic': 'fleq.s', 'handler': 'fleq.s', 'cost': 1, 'tags': 'ZFA_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fli.s', 'handler': 'fli.s', 'cost': 1, 'tags': 'ZFA_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fltq.s', 'handler': 'fltq.s', 'cost': 1, 'tags': 'ZFA_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fmaxm.s', 'handler': 'fmaxm.s', 'cost': 1, 'tags': 'ZFA_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fminm.s', 'handler': 'fminm.s', 'cost': 1, 'tags': 'ZFA_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fround.s', 'handler': 'fround.s', 'cost': 1, 'tags': 'ZFA_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'froundnx.s', 'handler': 'froundnx.s', 'cost': 1, 'tags': 'ZFA_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvtmod.w.d', 'handler': 'fcvtmod.w.d', 'cost': 1, 'tags': 'ZFA_EXT_64', 'memory': False, 'cof': False},

    {'mnemonic': 'fleq.d', 'handler': 'fleq.d', 'cost': 1, 'tags': 'ZFA_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fli.d', 'handler': 'fli.d', 'cost': 1, 'tags': 'ZFA_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fltq.d', 'handler': 'fltq.d', 'cost': 1, 'tags': 'ZFA_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fmaxm.d', 'handler': 'fmaxm.d', 'cost': 1, 'tags': 'ZFA_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fminm.d', 'handler': 'fminm.d', 'cost': 1, 'tags': 'ZFA_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fround.d', 'handler': 'fround.d', 'cost': 1, 'tags': 'ZFA_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'froundnx.d', 'handler': 'froundnx.d', 'cost': 1, 'tags': 'ZFA_EXT_64', 'memory': False, 'cof': False},
    #{'mnemonic': 'fleq.h', 'handler': 'fleq.h', 'cost': 1, 'tags': 'ZFA_EXT_64', 'memory': False, 'cof': False},
    #{'mnemonic': 'fli.h', 'handler': 'fli.h', 'cost': 1, 'tags': 'ZFA_EXT_64', 'memory': False, 'cof': False},
    #{'mnemonic': 'fltq.h', 'handler': 'fltq.h', 'cost': 1, 'tags': 'ZFA_EXT_64', 'memory': False, 'cof': False},
    #{'mnemonic': 'fmaxm.h', 'handler': 'fmaxm.h', 'cost': 1, 'tags': 'ZFA_EXT_64', 'memory': False, 'cof': False},
    #{'mnemonic': 'fminm.h', 'handler': 'fminm.h', 'cost': 1, 'tags': 'ZFA_EXT_64', 'memory': False, 'cof': False},
    #{'mnemonic': 'fround.h', 'handler': 'fround.h', 'cost': 1, 'tags': 'ZFA_EXT_64', 'memory': False, 'cof': False},
    #{'mnemonic': 'froundnx.h', 'handler': 'froundnx.h', 'cost': 1, 'tags': 'ZFA_EXT_64', 'memory': False, 'cof': False},
]
