RVZFH_MAVIS_EXTS = ["zfh", "zfhmin", "zfhmind"]

RV32ZFH_INST = [
    {'mnemonic': 'fmv.h.x', 'handler': 'fmv_h_x', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fmv.x.h', 'handler': 'fmv_x_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.h.w', 'handler': 'fcvt_h_w', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.h.wu', 'handler': 'fcvt_h_wu', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.w.h', 'handler': 'fcvt_w_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.wu.h', 'handler': 'fcvt_wu_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.h.s', 'handler': 'fcvt_h_s', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.s.h', 'handler': 'fcvt_s_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.h.d', 'handler': 'fcvt_h_d', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.d.h', 'handler': 'fcvt_d_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'flh', 'handler': 'flh', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'fsh', 'handler': 'fsh', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': True, 'cof': False},
    {'mnemonic': 'fadd.h', 'handler': 'fadd_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fsub.h', 'handler': 'fsub_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fmul.h', 'handler': 'fmul_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fdiv.h', 'handler': 'fdiv_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fsqrt.h', 'handler': 'fsqrt_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fmadd.h', 'handler': 'fmadd_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fmsub.h', 'handler': 'fmsub_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fnmsub.h', 'handler': 'fnmsub_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fnmadd.h', 'handler': 'fnmadd_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fsgnj.h', 'handler': 'fsgnj_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fsgnjn.h', 'handler': 'fsgnjn_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fsgnjx.h', 'handler': 'fsgnjx_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fmin.h', 'handler': 'fmin_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fmax.h', 'handler': 'fmax_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'feq.h', 'handler': 'feq_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'flt.h', 'handler': 'flt_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fle.h', 'handler': 'fle_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
    {'mnemonic': 'fclass.h', 'handler': 'fclass_h', 'cost': 1, 'tags': 'ZFH_EXT_32', 'memory': False, 'cof': False},
]

RV64ZFH_INST = [
    {'mnemonic': 'fmv.h.x', 'handler': 'fmv_h_x', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fmv.x.h', 'handler': 'fmv_x_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.h.w', 'handler': 'fcvt_h_w', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.h.wu', 'handler': 'fcvt_h_wu', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.w.h', 'handler': 'fcvt_w_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.wu.h', 'handler': 'fcvt_wu_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.l.h', 'handler': 'fcvt_l_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.lu.h', 'handler': 'fcvt_lu_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.h.l', 'handler': 'fcvt_h_l', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.h.lu', 'handler': 'fcvt_h_lu', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.h.s', 'handler': 'fcvt_h_s', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.s.h', 'handler': 'fcvt_s_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.h.d', 'handler': 'fcvt_h_d', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fcvt.d.h', 'handler': 'fcvt_d_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'flh', 'handler': 'flh', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'fsh', 'handler': 'fsh', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': True, 'cof': False},
    {'mnemonic': 'fadd.h', 'handler': 'fadd_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fsub.h', 'handler': 'fsub_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fmul.h', 'handler': 'fmul_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fdiv.h', 'handler': 'fdiv_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fsqrt.h', 'handler': 'fsqrt_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fmadd.h', 'handler': 'fmadd_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fmsub.h', 'handler': 'fmsub_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fnmsub.h', 'handler': 'fnmsub_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fnmadd.h', 'handler': 'fnmadd_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fsgnj.h', 'handler': 'fsgnj_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fsgnjn.h', 'handler': 'fsgnjn_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fsgnjx.h', 'handler': 'fsgnjx_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fmin.h', 'handler': 'fmin_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fmax.h', 'handler': 'fmax_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'feq.h', 'handler': 'feq_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'flt.h', 'handler': 'flt_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fle.h', 'handler': 'fle_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
    {'mnemonic': 'fclass.h', 'handler': 'fclass_h', 'cost': 1, 'tags': 'ZFH_EXT_64', 'memory': False, 'cof': False},
]
