RVZVE64X_INST = [
    {'mnemonic': 'vle64.v', 'handler': 'vle64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False, 'veccfg': ['eew64']},
    {'mnemonic': 'vse64.v', 'handler': 'vse64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False, 'veccfg': ['eew64']},
    {'mnemonic': 'vlse64.v', 'handler': 'vlse64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False, 'veccfg': ['eew64']},
    {'mnemonic': 'vsse64.v', 'handler': 'vsse64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False, 'veccfg': ['eew64']},
    {'mnemonic': 'vloxei64.v', 'handler': 'vloxei64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False, 'veccfg': ['eew64']},
    {'mnemonic': 'vluxei64.v', 'handler': 'vluxei64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False, 'veccfg': ['eew64']},
    {'mnemonic': 'vsoxei64.v', 'handler': 'vsoxei64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False, 'veccfg': ['eew64']},
    {'mnemonic': 'vsuxei64.v', 'handler': 'vsuxei64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False, 'veccfg': ['eew64']},
    {'mnemonic': 'vle64ff.v', 'handler': 'vle64ff.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False, 'veccfg': ['eew64']},
    {'mnemonic': 'vl1re64.v', 'handler': 'vl1re64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False, 'veccfg': ['eew64', 'emul1', 'vlmax']},
    {'mnemonic': 'vl2re64.v', 'handler': 'vl2re64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False, 'veccfg': ['eew64', 'emul2', 'vlmax']},
    {'mnemonic': 'vl4re64.v', 'handler': 'vl4re64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False, 'veccfg': ['eew64', 'emul4', 'vlmax']},
    {'mnemonic': 'vl8re64.v', 'handler': 'vl8re64.v', 'cost': 1, 'tags': 'V_EXT_64', 'memory': True, 'cof': False, 'veccfg': ['eew64', 'emul8', 'vlmax']},
]
