#pragma once

// This file is autogenerated using: /home/kathlenemagnus/forks/elliottgurrola-mips/pegasus/scripts/GenInstructionJSON.py --supported-isa rv32

#define SUPPORTED_ISA_STR   "i_m_a_f_d_zba_zbb_zbc_zbs_zicsr_zifencei_zicbop_zicbom_zicboz_zicond_zcmp_zve64x_zve64d_zve32x_zve32f_zihintntl_zihintpause"
#define DEFAULT_ISA_STR     "i_m_a_f_d_zba_zbb_zbc_zbs_zicsr_zifencei_zicbop_zicbom_zicboz_zicond_zcmp_zve64x_zve64d_zve32x_zve32f_zihintntl_zihintpause"
