"""
Generated by Cursor

Used to generate the Pegasus instruction handler classes for any missing
extensions supported by Mavis.
"""
import json
import re
from pathlib import Path
from typing import List, Set


ROOT = Path(__file__).resolve().parents[1]
JSON_DIR = ROOT / "mavis" / "json"
HANDLERS_DIR = ROOT / "core" / "inst_handlers"


def ext_from_filename(name: str) -> str:
    """
    Extract extension suffix from isa_rv64*.json.
    Example: isa_rv64zicond.json -> zicond
    """
    m = re.match(r"isa_rv64(.*)\.json$", name)
    if not m:
        raise ValueError(f"Unexpected filename format: {name}")
    return m.group(1)


def find_existing_exts() -> Set[str]:
    """
    Find existing Rv*Insts.hpp classes and derive their ext names.
    Example: RvzicondInsts.hpp -> zicond, RviInsts.hpp -> i
    """
    base = Path(HANDLERS_DIR)
    exts: Set[str] = set()
    for path in base.rglob("Rv*Insts.hpp"):
        stem = path.stem  # e.g. RvzicondInsts
        if not (stem.startswith("Rv") and stem.endswith("Insts")):
            continue
        core = stem[2:-5]  # strip leading 'Rv' and trailing 'Insts'
        if core:
            exts.add(core.lower())
    return exts


HEADER_TEMPLATE = """#pragma once

#include "core/InstHandlers.hpp"

namespace pegasus
{{
    class PegasusState;

    class {class_name}
    {{
      public:
        using base_type = {class_name};

        template <typename XLEN> static void getInstHandlers(InstHandlers::InstHandlersMap &);
    }};
}} // namespace pegasus
"""


CPP_TEMPLATE = """#include "core/inst_handlers/{ext}/{class_name}.hpp"
#include "core/inst_handlers/i/RviInsts.hpp"
#include "include/ActionTags.hpp"

namespace pegasus
{{
    template <typename XLEN>
    void {class_name}::getInstHandlers(InstHandlers::InstHandlersMap & inst_handlers)
    {{
        static_assert(std::is_same_v<XLEN, RV64> || std::is_same_v<XLEN, RV32>);

{body}
    }}

{instantiations}
}} // namespace pegasus
"""

def load_mnemonics(json_path: Path) -> List[str]:
    with json_path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    mns: List[str] = []
    for entry in data:
        if isinstance(entry, dict):
            m = entry.get("mnemonic")
            if isinstance(m, str):
                mns.append(m)
    # preserve order but unique
    seen: Set[str] = set()
    unique: List[str] = []
    for m in mns:
        if m not in seen:
            seen.add(m)
            unique.append(m)
    return unique


def main() -> None:
    existing_exts = find_existing_exts()
    json_dir = Path(JSON_DIR)

    exts = {}
    for json_path in sorted(json_dir.glob("isa_rv64*.json")):
        ext = ext_from_filename(json_path.name)
        ext_base = ext
        if '_' in ext:
            ext_base = ext.split('_')[0]

        if ext_base not in exts.keys():
            exts[ext_base] = []
        exts[ext_base].append(json_path)

    for ext, jsons in exts.items():
        if ext.lower() in existing_exts:
            # There is already a handler class like Rv{ext}Insts.hpp; skip.
            continue

        class_name = f"Rv{ext}Insts"
        subdir = Path(HANDLERS_DIR) / ext
        subdir.mkdir(parents=True, exist_ok=True)

        header_path = subdir / f"{class_name}.hpp"
        cpp_path = subdir / f"{class_name}.cpp"

        mnemonics = []
        for json_path in jsons:
            mnemonics.extend(load_mnemonics(json_path))

        if not mnemonics:
            # Nothing to register, skip creating files.
            continue

        if not header_path.exists():
            header_code = HEADER_TEMPLATE.format(class_name=class_name)
            header_path.write_text(header_code, encoding="utf-8")

        if not cpp_path.exists():
            # one line per emplace; newlines come from join()
            body_lines: List[str] = []
            body_lines.append('        (void)inst_handlers;')
            for mnem in mnemonics:
                inst = mnem.replace('.', '_')
                body_lines.append(
                    f'        //inst_handlers.emplace("{inst}", '
                    f'pegasus::Action::createAction<&{class_name}::, {class_name}>('
                    f'"{inst}", ActionTags::EXECUTE_TAG));'
                )
            body = "\n".join(body_lines)

            # Only instantiate XLENs that have matching mavis/json files
            has_rv32 = (json_dir / f"isa_rv32{ext}.json").exists()
            has_rv64 = (json_dir / f"isa_rv64{ext}.json").exists()

            inst_lines: List[str] = []
            if has_rv32:
                inst_lines.append(
                    f"    template void {class_name}"
                    "::getInstHandlers<RV32>(InstHandlers::InstHandlersMap &);"
                )
            if has_rv64:
                inst_lines.append(
                    f"    template void {class_name}"
                    "::getInstHandlers<RV64>(InstHandlers::InstHandlersMap &);"
                )
            instantiations = "\n".join(inst_lines)

            cpp_code = CPP_TEMPLATE.format(
                ext=ext,
                class_name=class_name,
                body=body,
                instantiations=instantiations,
            )
            cpp_path.write_text(cpp_code, encoding="utf-8")
            

if __name__ == "__main__":
    main()

