#!/usr/bin/env python3
"""Helper script for generating instruction uarch JSONs.
"""

from enum import Enum
import importlib.util
import json
import math
import sys
import os
import copy


# Generated by Cursor
def _load_inst_headers():
    """Discover all *_INST.py modules in insts/ and collect their INST lists and MAVIS_EXTS."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    insts_dir = os.path.join(script_dir, 'insts')

    exports = {}
    for filename in sorted(os.listdir(insts_dir)):
        if not filename.endswith('_INST.py'):
            continue

        modname = 'insts.' + filename[:-3]
        spec = importlib.util.spec_from_file_location(modname, os.path.join(insts_dir, filename))
        if spec is None or spec.loader is None:
            continue
        mod = importlib.util.module_from_spec(spec)
        sys.modules[modname] = mod
        spec.loader.exec_module(mod)
        for name in dir(mod):
            if (name.endswith('_INST') or 'MAVIS_EXTS' in name) and not name.startswith('_'):
                exports[name] = getattr(mod, name)
    return exports


# Inject all INST lists and MAVIS_EXTS from insts/*_INST.py into this module's globals
for _name, _value in _load_inst_headers().items():
    globals()[_name] = _value


class InstJSONGenerator():
    """Generates instruction definition JSON files.

    Args:
        xlen (str): RISC-V XLEN string (e.g. "32" or "64")
        extensions (list): List of supported extensions (e.g. "i", "v", "zicsr")
    """
    def __init__(self, xlen, pegasus_uarch_jsons):
        self.xlen = xlen
        self.pegasus_uarch_jsons = pegasus_uarch_jsons
        self.isa_map = {}

        for ext in self.pegasus_uarch_jsons:
            xlen_str = "" if "zve" in ext else str(self.xlen)
            global_str = "RV" + xlen_str + ext.upper() + "_INST"
            if global_str in globals().keys():
                self.isa_map[ext] = globals()[global_str]
                for inst in self.isa_map[ext]:
                    inst['xlen'] = self.xlen
                # Sort alphabetically
                self.isa_map[ext] = sorted(self.isa_map[ext], key=lambda x: x['mnemonic'])
            #else:
            #    print("WARNING: Missing:", global_str)

    def write_jsons(self, arch_name):
        """Write register definitions to a JSON file in the given directory"""
        xlen_str = "rv"+str(self.xlen)
        gen_path = os.path.join(arch_name, xlen_str, 'gen')

        if not os.path.isdir(gen_path):
            os.makedirs(gen_path)

        for ext, insts in self.isa_map.items():
            filename = os.path.join(gen_path, "pegasus_uarch_" + xlen_str + ext.lower() + ".json")
            with open(filename,"w") as fh:
                json.dump(self.isa_map[ext], fh, indent=4)

def get_supported_exts():
    ''' Generates a string with all of the available extensions imported.
        The format of the returned string is xlen_extension1_extension2_...'''
    rv64_exts = list()
    rv32_exts = list()

    for var in globals().keys():
        if "MAVIS_EXTS" in var:
            if "64" in var:
                rv64_exts.extend(globals()[var])
            elif "32" in var:
                rv32_exts.extend(globals()[var])
            else:
                rv64_exts.extend(globals()[var])
                rv32_exts.extend(globals()[var])
        else:
            continue

    return (rv64_exts, rv32_exts)

def get_pegasus_uarch_jsons():
    ''' Generates a string with all of the available extensions imported.
        The format of the returned string is xlen_extension1_extension2_...'''
    rv64_jsons = list()
    rv32_jsons = list()

    for var in globals().keys():
        if "RV" in var and "MAVIS" not in var:
            var = var.replace("_INST", "")
            var = var.lower()
            if "rv64" in var:
                var = var.replace("rv64", "")
                rv64_jsons.append(var)
            elif "rv32" in var:
                var = var.replace("rv32", "")
                rv32_jsons.append(var)
            else:
                var = var.replace("rv", "")
                rv64_jsons.append(var)
                rv32_jsons.append(var)
        else:
            continue

    return (rv64_jsons, rv32_jsons)

def gen_supported_isa_header(arch_root, supported_rv64_exts, supported_rv32_exts, pegasus_uarch_rv64_jsons, pegasus_uarch_rv32_jsons):
    ''' Writes header file with ISA defines '''
    default_isa = "imafdcbv_zicsr_zifencei"

    gen_path = 'gen'
    if not os.path.isdir(gen_path):
        os.makedirs(gen_path)

    with open( os.path.join(gen_path, 'supportedISA.hpp'), 'w' ) as fh:
        fh.write( '#pragma once\n\n' )
        cmdline = ' '.join(sys.argv)
        fh.write( f'// This file is autogenerated using: {cmdline}\n\n' )
        fh.write( f'#define DEFAULT_ISA_STR "{default_isa}"\n' )
        fh.write('#define SUPPORTED_RV64_EXTS {\\\n')
        for idx, ext in enumerate(supported_rv64_exts):

            if idx == (len(supported_rv64_exts) - 1):
                fh.write( f'    \"{ext}\" }}\n')
            else:
                fh.write( f'    \"{ext}\", \\\n')
        fh.write('#define SUPPORTED_RV32_EXTS {\\\n')
        for idx, ext in enumerate(supported_rv32_exts):
            # Last extension in the list
            if idx == (len(supported_rv32_exts) - 1):
                fh.write( f'    \"{ext}\" }}\n')
            else:
                fh.write( f'    \"{ext}\", \\\n')


def get_profile_supported_exts(profile, mavis_profile_json, RV64_PEGASUS_SUPPORTED_EXTS, RV32_PEGASUS_SUPPORTED_EXTS):
    with open(mavis_profile_json, 'r') as file:
        data = json.load(file)

    isa = data["profiles"][profile]

    profile_exts = isa.split("_")
    base_isa = copy.deepcopy(profile_exts[0])

    # Validate ISA string, always starts with rv
    if (base_isa[0:2] != "rv"):
        print("ERROR: Invalid RISC-V profile:", profile)
        sys.exit(1)
    base_isa = base_isa[2:]

    # XLEN
    profile_xlen = 64
    try:
        profile_xlen = int(base_isa[0:2])
    except ValueError:
        print("ERROR: Invalid RISC-V profile:", profile)
        sys.exit(1)
    base_isa = base_isa[2:]

    profile_exts[0] = base_isa[0]
    base_isa = base_isa[1:]
    for ext in base_isa:
        profile_exts.append(ext)

    SUPPORTED_EXTENSIONS = RV64_PEGASUS_SUPPORTED_EXTS if (profile_xlen == 64) else RV64_PEGASUS_SUPPORTED_EXTS
    exts = []
    for ext in profile_exts:
        if ext in SUPPORTED_EXTENSIONS:
            exts.append(ext)
        #else:
        #    print("WARNING: Extension not supported by Pegasus:", ext)

    return exts
