#

CSR32_DEFS = {
    # User Trap Setup
    0x000: {
             'name': 'ustatus',
             'desc': 'User status register.',
             'fields': {},
             'context': 'HART',
           },
    0x004: {
             'name': 'uie',
             'desc': 'User interrupt-enable register.',
             'fields': {},
             'context': 'HART',
           },
    0x005: {
             'name': 'utvec',
             'desc': 'User trap handler base address.',
             'fields': {},
             'context': 'HART',
           },

    # Debug
    0x010: {
             'name': 'dmcontrol',
             'desc': 'Debug module control',
             'fields': {
               'haltreq'         : { 'high_bit': 31, 'low_bit':  31, 'readonly': False, 'desc': 'Halt request for currently selected harts' },
               'resumereq'       : { 'high_bit': 30, 'low_bit':  30, 'readonly': False, 'desc': 'Resume request for currently selected harts' },
               'hartreset'       : { 'high_bit': 29, 'low_bit':  29, 'readonly': False, 'desc': 'Writes reset bit for all currently selected harts' },
               'ackhavereset'    : { 'high_bit': 28, 'low_bit':  28, 'readonly': False, 'desc': 'If set, clears havereset for any selected harts' },
               'Resv'            : { 'high_bit':  5, 'low_bit':   4, 'readonly': True , 'desc': 'undocumented' },
               'hasel'           : { 'high_bit': 26, 'low_bit':  26, 'readonly': True , 'desc': 'Selects the definition of hartsel' },
               'hartsello'       : { 'high_bit': 25, 'low_bit':  16, 'readonly': False, 'desc': 'Low 10 bits of hartsel' },
               'hartselhi'       : { 'high_bit': 15, 'low_bit':   6, 'readonly': False, 'desc': 'High 10 bits of hartsel' },
               'setresethartreq' : { 'high_bit':  3, 'low_bit':   3, 'readonly': False, 'desc': 'Writes halt-on-reset request bit for all currently selected harts' },
               'clrresethaltreq' : { 'high_bit':  2, 'low_bit':   2, 'readonly': False, 'desc': 'Clears halt-on-reset request bit for all currently selected harts' },
               'ndmreset'        : { 'high_bit':  1, 'low_bit':   1, 'readonly': False, 'desc': 'Controls the reset signal from the DM to the rest of the system' },
               'dmactive'        : { 'high_bit':  0, 'low_bit':   0, 'readonly': False, 'desc': 'Reset signal for the Debug Module itself' },
             },
             'context': 'HART',
           },
    0x011: {
             'name': 'dmstatus',
             'desc': 'Debug module status',
             'fields': {
               'Resv'            : { 'high_bit': 21, 'low_bit':  20, 'readonly': True , 'desc': 'undocumented' },
               'impebreak'       : { 'high_bit': 22, 'low_bit':  22, 'readonly': False, 'desc': 'undocumented' },
               'allhavereset'    : { 'high_bit': 19, 'low_bit':  19, 'readonly': False, 'desc': 'undocumented' },
               'anyhavereset'    : { 'high_bit': 18, 'low_bit':  18, 'readonly': False, 'desc': 'undocumented' },
               'allresumeack'    : { 'high_bit': 17, 'low_bit':  17, 'readonly': False, 'desc': 'undocumented' },
               'anyresumeack'    : { 'high_bit': 16, 'low_bit':  16, 'readonly': False, 'desc': 'undocumented' },
               'allnonexistent'  : { 'high_bit': 15, 'low_bit':  15, 'readonly': False, 'desc': 'undocumented' },
               'anynonexistent'  : { 'high_bit': 14, 'low_bit':  14, 'readonly': False, 'desc': 'undocumented' },
               'allunavail'      : { 'high_bit': 13, 'low_bit':  13, 'readonly': False, 'desc': 'undocumented' },
               'anyunavail'      : { 'high_bit': 12, 'low_bit':  12, 'readonly': False, 'desc': 'undocumented' },
               'allrunning'      : { 'high_bit': 11, 'low_bit':  11, 'readonly': False, 'desc': 'undocumented' },
               'anyrunning'      : { 'high_bit': 10, 'low_bit':  10, 'readonly': False, 'desc': 'undocumented' },
               'allhalted'       : { 'high_bit':  9, 'low_bit':   9, 'readonly': False, 'desc': 'undocumented' },
               'anyhalted'       : { 'high_bit':  8, 'low_bit':   8, 'readonly': False, 'desc': 'undocumented' },
               'authenticated'   : { 'high_bit':  7, 'low_bit':   7, 'readonly': True , 'desc': "Status of authentication (set to 1 if DM doesn't implement authentication)" },
               'authbusy'        : { 'high_bit':  6, 'low_bit':   6, 'readonly': False, 'desc': 'Authentication module is ready to process the next read/write to authdata' },
               'hasresethaltreq' : { 'high_bit':  5, 'low_bit':   5, 'readonly': True , 'desc': 'If set, this Debug Module supports halt-on-reset' },
               'confstrptrvalid' : { 'high_bit':  4, 'low_bit':   4, 'readonly': True , 'desc': 'If set, confstrptr0-confstrptr3 hold the address of the configuration string' },
               'version'         : { 'high_bit':  3, 'low_bit':   0, 'readonly': True , 'desc': 'Version of Debug Module spec supported' },
             },
             'context': 'HART',
           },

    # Zcmt: User Jump table
    0x017: {
             'name': 'jvt',
             'desc': 'Table jump base vector and control register',
             'fields': {
               'BASE' : { 'high_bit': 31, 'low_bit':   6, 'readonly': False, 'desc': 'Jump Table base address' },
               'MODE' : { 'high_bit':  5, 'low_bit':   0, 'readonly': False, 'desc': 'Jump Table mode' },
             },
             'extension': ['Zcmt'],
             'context': 'HART',
           },

    # User Trap Setup
    0x040: {
             'name': 'uscratch',
             'desc': 'Scratch register for user trap handlers.',
             'fields': {},
             'context': 'HART',
           },
    0x041: {
             'name': 'uepc',
             'desc': 'User exception program counter.',
             'fields': {},
             'context': 'HART',
           },
    0x042: {
             'name': 'ucause',
             'desc': 'Scratch register for user trap handlers.',
             'fields': {},
             'context': 'HART',
           },
    0x043: {
             'name': 'utval',
             'desc': 'User bad address or instruction.',
             'fields': {},
             'context': 'HART',
           },
    0x044: {
             'name': 'uip',
             'desc': 'User interrupt pending.',
             'fields': {},
             'context': 'HART',
           },

    # User Floating-Point CSRs
    0x001: {
             'name': 'fflags',
             'desc': 'Floating-Point Accrued Exceptions.',
             'fields': {
               'Resv' : { 'high_bit': 31, 'low_bit':   5, 'readonly': True , 'desc': 'undocumented' },
               'NV'   : { 'high_bit':  4, 'low_bit':   4, 'readonly': False, 'desc': 'Invalid operation' },
               'DZ'   : { 'high_bit':  3, 'low_bit':   3, 'readonly': False, 'desc': 'Divide by zero' },
               'OF'   : { 'high_bit':  2, 'low_bit':   2, 'readonly': False, 'desc': 'Overflow' },
               'UF'   : { 'high_bit':  1, 'low_bit':   1, 'readonly': False, 'desc': 'Underflow' },
               'NX'   : { 'high_bit':  0, 'low_bit':   0, 'readonly': False, 'desc': 'Inexact' },
             },
             'context': 'HART',
           },
    0x002: {
             'name': 'frm',
             'desc': 'Floating-Point Dynamic Rounding Mode.',
             'fields': {},
             'context': 'HART',
           },
    0x003: {
             'name': 'fcsr',
             'desc': 'Floating-Point Control and Status Register (frm + fflags).',
             'fields': {
               'Resv'   : { 'high_bit': 31, 'low_bit':   8, 'readonly': True , 'desc': 'undocumented' },
               'frm'    : { 'high_bit':  7, 'low_bit':   5, 'readonly': False, 'desc': 'Rounding Mode' },
               'NV'     : { 'high_bit':  4, 'low_bit':   4, 'readonly': False, 'desc': 'Invalid Operation' },
               'DZ'     : { 'high_bit':  3, 'low_bit':   3, 'readonly': False, 'desc': 'Divide by zero' },
               'OF'     : { 'high_bit':  2, 'low_bit':   2, 'readonly': False, 'desc': 'Overflow' },
               'UF'     : { 'high_bit':  1, 'low_bit':   1, 'readonly': False, 'desc': 'Underflow' },
               'NX'     : { 'high_bit':  0, 'low_bit':   0, 'readonly': False, 'desc': 'Inexact' },
               'fflags' : { 'high_bit':  4, 'low_bit':   0, 'readonly': False, 'desc': 'Accured Exceptions' },
             },
             'context': 'HART',
           },

    # User Vector CSRs
    0x008: {
             'name': 'vstart',
             'desc': 'The index of the first element to be executed by a vector instruction.',
             'fields': {},
             'context': 'HART',
           },
    0x009: {
             'name': 'vxsat',
             'desc': 'To indicate whether a fixed-point instruction needs to saturate.',
             'fields': {
               'vxsat' : { 'high_bit':  0, 'low_bit':   0, 'readonly': False, 'desc': 'Saturate' },
               'Resv'  : { 'high_bit': 31, 'low_bit':   1, 'readonly': True , 'desc': 'undocumented' },
             },
             'context': 'HART',
           },
    0x00A: {
             'name': 'vxrm',
             'desc': 'Vector fixed-point rounding-mode register.',
             'fields': {
               'vxrm' : { 'high_bit':  1, 'low_bit':   0, 'readonly': False, 'desc': 'Rounding mode' },
               'Resv' : { 'high_bit': 31, 'low_bit':   2, 'readonly': True , 'desc': 'undocumented' },
             },
             'context': 'HART',
           },
    0x00F: {
             'name': 'vcsr',
             'desc': 'Vector control and status register.',
             'fields': {
               'vxsat' : { 'high_bit':  0, 'low_bit':   0, 'readonly': False, 'desc': 'Fixed-point accrued saturation flag' },
               'vxrm'  : { 'high_bit':  2, 'low_bit':   1, 'readonly': False, 'desc': 'Fixed-point rounding mode' },
               'Resv'  : { 'high_bit': 31, 'low_bit':   3, 'readonly': True , 'desc': 'undocumented' },
             },
             'context': 'HART',
           },
    0xC20: {
             'name': 'vl',
             'desc': 'Vector legnth register.',
             'fields': {},
             'context': 'HART',
           },
    0xC21: {
             'name': 'vtype',
             'desc': 'Vector type register.',
             'fields': {
               'vlmul' : { 'high_bit':  2, 'low_bit':   0, 'readonly': False, 'desc': 'Vector register group multiplier' },
               'vsew'  : { 'high_bit':  5, 'low_bit':   3, 'readonly': False, 'desc': 'Selected element width' },
               'vta'   : { 'high_bit':  6, 'low_bit':   6, 'readonly': False, 'desc': 'Vector tail agnostic mode' },
               'vma'   : { 'high_bit':  7, 'low_bit':   7, 'readonly': False, 'desc': 'Vector mask agnostic mode' },
               'Resv'  : { 'high_bit': 30, 'low_bit':   8, 'readonly': True , 'desc': 'undocumented' },
               'vill'  : { 'high_bit': 31, 'low_bit':  31, 'readonly': False, 'desc': 'Illegal value if set' },
             },
             'context': 'HART',
           },
    0xC22: {
             'name': 'vlenb',
             'desc': 'Vector byte length.',
             'fields': {},
             'context': 'HART',
           },

    # User Counter/Timers
    0xC00: {
             'name': 'cycle',
             'desc': 'Cycle counter for RDCYCLE instruction.',
             'fields': {},
             'context': 'HART',
           },
    0xC01: {
             'name': 'time',
             'desc': 'Timer for RDTIME instruction.',
             'fields': {},
             'context': 'HART',
           },
    0xC02: {
             'name': 'instret',
             'desc': 'Instructions-retired counter for RDINSTRET instruction.',
             'fields': {},
             'context': 'HART',
           },
    0xC03: {
             'name': 'hpmcounter3',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC04: {
             'name': 'hpmcounter4',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC05: {
             'name': 'hpmcounter5',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC06: {
             'name': 'hpmcounter6',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC07: {
             'name': 'hpmcounter7',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC08: {
             'name': 'hpmcounter8',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC09: {
             'name': 'hpmcounter9',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC0A: {
             'name': 'hpmcounter10',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC0B: {
             'name': 'hpmcounter11',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC0C: {
             'name': 'hpmcounter12',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC0D: {
             'name': 'hpmcounter13',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC0E: {
             'name': 'hpmcounter14',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC0F: {
             'name': 'hpmcounter15',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC10: {
             'name': 'hpmcounter16',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC11: {
             'name': 'hpmcounter17',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC12: {
             'name': 'hpmcounter18',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC13: {
             'name': 'hpmcounter19',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC14: {
             'name': 'hpmcounter20',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC15: {
             'name': 'hpmcounter21',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC16: {
             'name': 'hpmcounter22',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC17: {
             'name': 'hpmcounter23',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC18: {
             'name': 'hpmcounter24',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC19: {
             'name': 'hpmcounter25',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC1A: {
             'name': 'hpmcounter26',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC1B: {
             'name': 'hpmcounter27',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC1C: {
             'name': 'hpmcounter28',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC1D: {
             'name': 'hpmcounter29',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC1E: {
             'name': 'hpmcounter30',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xC1F: {
             'name': 'hpmcounter31',
             'desc': 'Performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },

    # RV32 only
    0xC80: {
             'name': 'cycleh',
             'desc': 'Upper 32 bits of cycle, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC81: {
             'name': 'timeh',
             'desc': 'Upper 32 bits of time, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC82: {
             'name': 'instreth',
             'desc': 'Upper 32 bits of instret, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC83: {
             'name': 'hpmcounter3h',
             'desc': 'Upper 32 bits of hpmcounter3, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC84: {
             'name': 'hpmcounter4h',
             'desc': 'Upper 32 bits of hpmcounter4, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC85: {
             'name': 'hpmcounter5h',
             'desc': 'Upper 32 bits of hpmcounter5, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC86: {
             'name': 'hpmcounter6h',
             'desc': 'Upper 32 bits of hpmcounter6, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC87: {
             'name': 'hpmcounter7h',
             'desc': 'Upper 32 bits of hpmcounter7, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC88: {
             'name': 'hpmcounter8h',
             'desc': 'Upper 32 bits of hpmcounter8, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC89: {
             'name': 'hpmcounter9h',
             'desc': 'Upper 32 bits of hpmcounter9, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC8A: {
             'name': 'hpmcounter10h',
             'desc': 'Upper 32 bits of hpmcounter10, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC8B: {
             'name': 'hpmcounter11h',
             'desc': 'Upper 32 bits of hpmcounter11, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC8C: {
             'name': 'hpmcounter12h',
             'desc': 'Upper 32 bits of hpmcounter12, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC8D: {
             'name': 'hpmcounter13h',
             'desc': 'Upper 32 bits of hpmcounter13, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC8E: {
             'name': 'hpmcounter14h',
             'desc': 'Upper 32 bits of hpmcounter14, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC8F: {
             'name': 'hpmcounter15h',
             'desc': 'Upper 32 bits of hpmcounter15, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC90: {
             'name': 'hpmcounter16h',
             'desc': 'Upper 32 bits of hpmcounter16, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC91: {
             'name': 'hpmcounter17h',
             'desc': 'Upper 32 bits of hpmcounter17, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC92: {
             'name': 'hpmcounter18h',
             'desc': 'Upper 32 bits of hpmcounter18, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC93: {
             'name': 'hpmcounter19h',
             'desc': 'Upper 32 bits of hpmcounter19, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC94: {
             'name': 'hpmcounter20h',
             'desc': 'Upper 32 bits of hpmcounter20, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC95: {
             'name': 'hpmcounter21h',
             'desc': 'Upper 32 bits of hpmcounter21, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC96: {
             'name': 'hpmcounter22h',
             'desc': 'Upper 32 bits of hpmcounter22, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC97: {
             'name': 'hpmcounter23h',
             'desc': 'Upper 32 bits of hpmcounter23, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC98: {
             'name': 'hpmcounter24h',
             'desc': 'Upper 32 bits of hpmcounter24, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC99: {
             'name': 'hpmcounter25h',
             'desc': 'Upper 32 bits of hpmcounter25, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC9A: {
             'name': 'hpmcounter26h',
             'desc': 'Upper 32 bits of hpmcounter26, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC9B: {
             'name': 'hpmcounter27h',
             'desc': 'Upper 32 bits of hpmcounter27, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC9C: {
             'name': 'hpmcounter28h',
             'desc': 'Upper 32 bits of hpmcounter28, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC9D: {
             'name': 'hpmcounter29h',
             'desc': 'Upper 32 bits of hpmcounter29, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC9E: {
             'name': 'hpmcounter30h',
             'desc': 'Upper 32 bits of hpmcounter30, RV32 only.',
             'fields': {},
             'context': 'HART',
           },
    0xC9F: {
             'name': 'hpmcounter31h',
             'desc': 'Upper 32 bits of hpmcounter31, RV32 only.',
             'fields': {},
             'context': 'HART',
           },

    # Supervisor Trap Setup
    0x100: {
             'name': 'sstatus',
             'desc': 'Supervisor status register.',
             'fields': {
               'SD'   : { 'high_bit': 31, 'low_bit':  31, 'readonly': False, 'desc': 'Fast-check bit: summarizes either FS/XS/VS set' },
               'WPRI' : { 'high_bit':  3, 'low_bit':   2, 'readonly': True , 'desc': 'resv' },
               'MXR'  : { 'high_bit': 19, 'low_bit':  19, 'readonly': False, 'desc': 'Make executable readable' },
               'SUM'  : { 'high_bit': 18, 'low_bit':  18, 'readonly': False, 'desc': 'Permit supervisor user memory access' },
               'XS'   : { 'high_bit': 16, 'low_bit':  15, 'readonly': False, 'desc': 'Extension status' },
               'FS'   : { 'high_bit': 14, 'low_bit':  13, 'readonly': False, 'desc': 'Floating-point status' },
               'VS'   : { 'high_bit': 10, 'low_bit':   9, 'readonly': False, 'desc': 'Vector status' },
               'SPP'  : { 'high_bit':  8, 'low_bit':   8, 'readonly': False, 'desc': 'Supervisor previous privilege mode' },
               'UBE'  : { 'high_bit':  6, 'low_bit':   6, 'readonly': False, 'desc': 'Controls endianness of explicit memory accesses made from U-mode' },
               'SPIE' : { 'high_bit':  5, 'low_bit':   5, 'readonly': False, 'desc': 'Indicates whether S-mode interrupts were enabled prior to trapping into S-mode' },
               'UPIE' : { 'high_bit':  4, 'low_bit':   4, 'readonly': False, 'desc': 'indicates whether U-mode interrupts were enabled prior to trapping into U-mode' },
               'SIE'  : { 'high_bit':  1, 'low_bit':   1, 'readonly': False, 'desc': 'Enable/Disable interrupts in S-mode' },
               'UIE'  : { 'high_bit':  0, 'low_bit':   0, 'readonly': False, 'desc': 'Enable/disable interrupts in U-mode' },
             },
             'context': 'HART',
           },
    0x102: {
             'name': 'sedeleg',
             'desc': 'Supervisor exception delegation register.',
             'fields': {},
             'context': 'HART',
           },
    0x103: {
             'name': 'sideleg',
             'desc': 'Supervisor interrupt delegation register.',
             'fields': {},
             'context': 'HART',
           },
    0x104: {
             'name': 'sie',
             'desc': 'Supervisor interrupt-enable register.',
             'fields': {
               'SEIE' : { 'high_bit':  9, 'low_bit':   9, 'readonly': False, 'desc': 'Enable supervisor-mode external interrupts' },
               'UEIE' : { 'high_bit':  8, 'low_bit':   8, 'readonly': False, 'desc': 'Enable user-mode external interrupts' },
               'WPRI' : { 'high_bit':  3, 'low_bit':   2, 'readonly': False, 'desc': 'undocumented' },
               'STIE' : { 'high_bit':  5, 'low_bit':   5, 'readonly': False, 'desc': 'Enable supervisor-mode timer interrupts' },
               'UTIE' : { 'high_bit':  4, 'low_bit':   4, 'readonly': False, 'desc': 'Enable user-mode timer interrupts' },
               'SSIE' : { 'high_bit':  1, 'low_bit':   1, 'readonly': False, 'desc': 'Enable supervisor-mode software interrupts' },
               'USIE' : { 'high_bit':  0, 'low_bit':   0, 'readonly': False, 'desc': 'Enable user-mode software interrupts' },
             },
             'context': 'HART',
           },
    0x105: {
             'name': 'stvec',
             'desc': 'Supervisor trap handler base address.',
             'fields': {
               'BASE' : { 'high_bit': 31, 'low_bit':   2, 'readonly': False, 'desc': 'Vector base address' },
               'MODE' : { 'high_bit':  1, 'low_bit':   0, 'readonly': False, 'desc': '0 - Direct, 1 - Vectored' },
             },
             'context': 'HART',
           },
    0x106: {
             'name': 'scounteren',
             'desc': 'Supervisor counter enable.',
             'fields': {},
             'context': 'HART',
           },

    # Supervisor Configuration
    0x10a: {
             'name': 'senvcfg',
             'desc': 'Supervisor environment configuration register.',
             'fields': {
               'WPRI'  : { 'high_bit': 31, 'low_bit':   8, 'readonly': False, 'desc': 'reserved' },
               'CBZE'  : { 'high_bit':  7, 'low_bit':   7, 'readonly': False, 'desc': 'Cache block zero instruction enable' },
               'CBCFE' : { 'high_bit':  6, 'low_bit':   6, 'readonly': False, 'desc': 'Cache block clean and flush instruction enable' },
               'CBIE'  : { 'high_bit':  5, 'low_bit':   4, 'readonly': False, 'desc': 'Cache block invalidate instruction enable' },
               'FIOM'  : { 'high_bit':  0, 'low_bit':   0, 'readonly': False, 'desc': 'Fence of I/O implies Memory' },
             },
             'context': 'HART',
           },

    # Ssstateen: Supervisor state enable registers
    0x10c: {
             'name': 'sstateen0',
             'desc': 'Supervisor State Enable Register 0',
             'fields': {
               'WPRI' : { 'high_bit': 31, 'low_bit':   3, 'readonly': True , 'desc': 'Reserved' },
               'JVT'  : { 'high_bit':  2, 'low_bit':   2, 'readonly': False, 'desc': 'JVT register access' },
               'FCSR' : { 'high_bit':  1, 'low_bit':   1, 'readonly': False, 'desc': 'FCSR register access' },
               'C'    : { 'high_bit':  0, 'low_bit':   0, 'readonly': True , 'desc': 'Custom state access' },
             },
             'extension': ['Ssstateen'],
             'context': 'HART',
           },
    0x10d: {
             'name': 'sstateen1',
             'desc': 'Supervisor State Enable Register 1',
             'fields': {},
             'extension': ['Ssstateen'],
             'context': 'HART',
           },
    0x10e: {
             'name': 'sstateen2',
             'desc': 'Supervisor State Enable Register 2',
             'fields': {},
             'extension': ['Ssstateen'],
             'context': 'HART',
           },
    0x10f: {
             'name': 'sstateen3',
             'desc': 'Supervisor State Enable Register 3',
             'fields': {},
             'extension': ['Ssstateen'],
             'context': 'HART',
           },

    # Supervisor Trap Handling
    0x140: {
             'name': 'sscratch',
             'desc': 'Scratch register for supervisor trap handlers.',
             'fields': {},
             'context': 'HART',
           },
    0x141: {
             'name': 'sepc',
             'desc': 'Supervisor exception program counter.',
             'fields': {},
             'context': 'HART',
           },
    0x142: {
             'name': 'scause',
             'desc': 'Supervisor trap cause.',
             'fields': {
               'Interrupt' : { 'high_bit': 31, 'low_bit':  31, 'readonly': False, 'desc': 'Bit to set a trap' },
               'Code'      : { 'high_bit': 30, 'low_bit':   0, 'readonly': False, 'desc': 'The exception code' },
             },
             'context': 'HART',
           },
    0x143: {
             'name': 'stval',
             'desc': 'Supervisor bad address or instruction.',
             'fields': {},
             'context': 'HART',
           },
    0x144: {
             'name': 'sip',
             'desc': 'Supervisor interrupt pending.',
             'fields': {
               'WPRI' : { 'high_bit':  3, 'low_bit':   2, 'readonly': False, 'desc': 'undocumented' },
               'SEIP' : { 'high_bit':  9, 'low_bit':   9, 'readonly': False, 'desc': 'Supervisor-mode external interrupt pending' },
               'UEIP' : { 'high_bit':  8, 'low_bit':   8, 'readonly': False, 'desc': 'User-mode external interrupts pending' },
               'STIP' : { 'high_bit':  5, 'low_bit':   5, 'readonly': False, 'desc': 'Supervisor-mode timer interrupt pending' },
               'UTIP' : { 'high_bit':  4, 'low_bit':   4, 'readonly': False, 'desc': 'User-mode Machine timer interrupt pending' },
               'SSIP' : { 'high_bit':  1, 'low_bit':   1, 'readonly': False, 'desc': 'Supervisor-mode software interrupt pending' },
               'USIP' : { 'high_bit':  0, 'low_bit':   0, 'readonly': False, 'desc': 'User-mode software interrupt pending' },
             },
             'context': 'HART',
           },

    # Sscsrind extension
    0x150: {
             'name': 'siselect',
             'desc': 'Supervisor Indirect Register Select',
             'fields': {},
             'extension': ['Sscsrind'],
             'context': 'HART',
           },
    0x151: {
             'name': 'sireg',
             'desc': 'Supervisor Indirect Register Alias',
             'fields': {},
             'extension': ['Sscsrind'],
             'context': 'HART',
           },
    0x152: {
             'name': 'sireg2',
             'desc': 'Supervisor Indirect Register Alias 2',
             'fields': {},
             'extension': ['Sscsrind'],
             'context': 'HART',
           },
    0x153: {
             'name': 'sireg3',
             'desc': 'Supervisor Indirect Register Alias 3',
             'fields': {},
             'extension': ['Sscsrind'],
             'context': 'HART',
           },
    0x154: {
             'name': 'sireg4',
             'desc': 'Supervisor Indirect Register Alias 4',
             'fields': {},
             'extension': ['Sscsrind'],
             'context': 'HART',
           },
    0x155: {
             'name': 'sireg5',
             'desc': 'Supervisor Indirect Register Alias 5',
             'fields': {},
             'extension': ['Sscsrind'],
             'context': 'HART',
           },
    0x156: {
             'name': 'sireg6',
             'desc': 'Supervisor Indirect Register Alias 6',
             'fields': {},
             'extension': ['Sscsrind'],
             'context': 'HART',
           },

    # Supervisor Protection and Translation
    0x180: {
             'name': 'satp',
             'desc': 'Supervisor address translation and protection.',
             'fields': {
               'MODE' : { 'high_bit': 31, 'low_bit':  31, 'readonly': False, 'desc': 'Type of translation' },
               'ASID' : { 'high_bit': 30, 'low_bit':  22, 'readonly': False, 'desc': 'Address space identifier' },
               'PPN'  : { 'high_bit': 21, 'low_bit':   0, 'readonly': False, 'desc': 'Physical page number' },
             },
             'context': 'HART',
           },

    # Machine Information Registers
    0xf11: {
             'name': 'mvendorid',
             'desc': 'Vendor ID.',
             'fields': {
               'Bank'   : { 'high_bit': 31, 'low_bit':   7, 'readonly': False, 'desc': 'The number of one-byte continuation codes' },
               'Offset' : { 'high_bit':  6, 'low_bit':   0, 'readonly': True , 'desc': 'Encodes the final byte' },
             },
             'context': 'HART',
           },
    0xf12: {
             'name': 'marchid',
             'desc': 'Architecture ID.',
             'fields': {},
             'context': 'HART',
           },
    0xf13: {
             'name': 'mimpid',
             'desc': 'Implementation ID.',
             'fields': {},
             'context': 'HART',
           },
    0xf14: {
             'name': 'mhartid',
             'desc': 'Hardware thread ID.',
             'fields': {},
             'context': 'HART',
           },
    0xf15: {
             'name': 'mconfigptr',
             'desc': 'Pointer to configuration data structure',
             'fields': {},
             'context': 'HART',
           },

    # Machine Trap Setup
    0x300: {
             'name': 'mstatus',
             'desc': 'Machine status register.',
             'fields': {
               'SD'   : { 'high_bit': 31, 'low_bit':  31, 'readonly': True , 'desc': 'Fast-check bit: summarizes either FS/XS/VS set' },
               'WPRI' : { 'high_bit':  2, 'low_bit':   2, 'readonly': True , 'desc': 'reserved' },
               'TSR'  : { 'high_bit': 22, 'low_bit':  22, 'readonly': False, 'desc': 'Trap SRET' },
               'TW'   : { 'high_bit': 21, 'low_bit':  21, 'readonly': False, 'desc': 'Timeout Wait' },
               'TVM'  : { 'high_bit': 20, 'low_bit':  20, 'readonly': False, 'desc': 'Trap Virtual Memory' },
               'MXR'  : { 'high_bit': 19, 'low_bit':  19, 'readonly': False, 'desc': 'Make executable readable' },
               'SUM'  : { 'high_bit': 18, 'low_bit':  18, 'readonly': False, 'desc': 'Permit supervisor user memory access' },
               'MPRV' : { 'high_bit': 17, 'low_bit':  17, 'readonly': False, 'desc': 'Modify Privilege' },
               'XS'   : { 'high_bit': 16, 'low_bit':  15, 'readonly': False, 'desc': 'Extension status' },
               'FS'   : { 'high_bit': 14, 'low_bit':  13, 'readonly': False, 'desc': 'Floating-point status' },
               'MPP'  : { 'high_bit': 12, 'low_bit':  11, 'readonly': False, 'desc': 'Machine previous privilege mode' },
               'VS'   : { 'high_bit': 10, 'low_bit':   9, 'readonly': False, 'desc': 'Vector status' },
               'SPP'  : { 'high_bit':  8, 'low_bit':   8, 'readonly': False, 'desc': 'Supervisor previous privilege mode' },
               'MPIE' : { 'high_bit':  7, 'low_bit':   7, 'readonly': False, 'desc': 'Indicates whether M-mode interrupts were enabled prior to trapping into M-mode' },
               'UBE'  : { 'high_bit':  6, 'low_bit':   6, 'readonly': False, 'desc': 'Controls endianness of explicit memory accesses made from U-mode' },
               'SPIE' : { 'high_bit':  5, 'low_bit':   5, 'readonly': False, 'desc': 'Indicates whether S-mode interrupts were enabled prior to trapping into S-mode' },
               'UPIE' : { 'high_bit':  4, 'low_bit':   4, 'readonly': False, 'desc': 'indicates whether U-mode interrupts were enabled prior to trapping into U-mode' },
               'MIE'  : { 'high_bit':  3, 'low_bit':   3, 'readonly': False, 'desc': 'Enable/Disable interrupts in M-mode' },
               'SIE'  : { 'high_bit':  1, 'low_bit':   1, 'readonly': False, 'desc': 'Enable/Disable interrupts in S-mode' },
               'UIE'  : { 'high_bit':  0, 'low_bit':   0, 'readonly': False, 'desc': 'Enable/disable interrupts in U-mode' },
             },
             'context': 'HART',
           },
    0x301: {
             'name': 'misa',
             'desc': 'ISA and extension.',
             'fields': {
               'MXL'        : { 'high_bit': 31, 'low_bit':  30, 'readonly': False, 'desc': 'Machine XLEN' },
               'WLRL'       : { 'high_bit': 29, 'low_bit':  26, 'readonly': False, 'desc': 'Unknown' },
               'Extensions' : { 'high_bit': 25, 'low_bit':   0, 'readonly': False, 'desc': 'Encodes the native base integer ISA' },
               'A'          : { 'high_bit':  0, 'low_bit':   0, 'readonly': False, 'desc': 'Atomic extension' },
               'B'          : { 'high_bit':  1, 'low_bit':   1, 'readonly': False, 'desc': 'Bit Manipulation extension' },
               'C'          : { 'high_bit':  2, 'low_bit':   2, 'readonly': False, 'desc': 'Compressed extension' },
               'D'          : { 'high_bit':  3, 'low_bit':   3, 'readonly': False, 'desc': 'Double-precision extension' },
               'E'          : { 'high_bit':  4, 'low_bit':   4, 'readonly': True , 'desc': 'RV32E extension' },
               'F'          : { 'high_bit':  5, 'low_bit':   5, 'readonly': False, 'desc': 'Single-precision extension' },
               'G'          : { 'high_bit':  6, 'low_bit':   6, 'readonly': True , 'desc': 'Reserved' },
               'H'          : { 'high_bit':  7, 'low_bit':   7, 'readonly': True , 'desc': 'Hypervisor extension' },
               'I'          : { 'high_bit':  8, 'low_bit':   8, 'readonly': False, 'desc': 'RV32I/64I/128I base ISA extension' },
               'J'          : { 'high_bit':  9, 'low_bit':   9, 'readonly': True , 'desc': 'Reserved' },
               'K'          : { 'high_bit': 10, 'low_bit':  10, 'readonly': True , 'desc': 'Reserved' },
               'L'          : { 'high_bit': 11, 'low_bit':  11, 'readonly': True , 'desc': 'Reserved' },
               'M'          : { 'high_bit': 12, 'low_bit':  12, 'readonly': False, 'desc': 'Integer Multiply/Divide extension' },
               'N'          : { 'high_bit': 13, 'low_bit':  13, 'readonly': True , 'desc': 'Reserved' },
               'O'          : { 'high_bit': 14, 'low_bit':  14, 'readonly': True , 'desc': 'Reserved' },
               'P'          : { 'high_bit': 15, 'low_bit':  15, 'readonly': True , 'desc': 'Reserved' },
               'Q'          : { 'high_bit': 16, 'low_bit':  16, 'readonly': True , 'desc': 'Quad-precision floating-point extension' },
               'R'          : { 'high_bit': 17, 'low_bit':  17, 'readonly': True , 'desc': 'Reserved' },
               'S'          : { 'high_bit': 18, 'low_bit':  18, 'readonly': False, 'desc': 'Supervisor mode implemented' },
               'T'          : { 'high_bit': 19, 'low_bit':  19, 'readonly': True , 'desc': 'Reserved' },
               'U'          : { 'high_bit': 20, 'low_bit':  20, 'readonly': False, 'desc': 'User mode implemented' },
               'V'          : { 'high_bit': 21, 'low_bit':  21, 'readonly': True , 'desc': 'Vector extension' },
               'W'          : { 'high_bit': 22, 'low_bit':  22, 'readonly': True , 'desc': 'Reserved' },
               'X'          : { 'high_bit': 23, 'low_bit':  23, 'readonly': False, 'desc': 'Non-standard extensions' },
               'Y'          : { 'high_bit': 24, 'low_bit':  24, 'readonly': True , 'desc': 'Reserved' },
               'Z'          : { 'high_bit': 25, 'low_bit':  25, 'readonly': True , 'desc': 'Reserved' },
             },
             'context': 'HART',
           },
    0x302: {
             'name': 'medeleg',
             'desc': 'Machine exception delegation register.',
             'fields': {},
             'context': 'HART',
           },
    0x303: {
             'name': 'mideleg',
             'desc': 'Machine interrupt delegation register.',
             'fields': {},
             'context': 'HART',
           },
    0x304: {
             'name': 'mie',
             'desc': 'Machine interrupt-enable register.',
             'fields': {
               'WPRI'  : { 'high_bit': 31, 'low_bit':  13, 'readonly': True , 'desc': 'reserved' },
               'SGEIE' : { 'high_bit': 12, 'low_bit':  12, 'readonly': False, 'desc': 'Enable supervisor guest external interrupts' },
               'MEIE'  : { 'high_bit': 11, 'low_bit':  11, 'readonly': False, 'desc': 'Enable machine-mode external interrupts' },
               'VSEIE' : { 'high_bit': 10, 'low_bit':  10, 'readonly': False, 'desc': 'Enable virtuall supervisor-mode external interrupts' },
               'SEIE'  : { 'high_bit':  9, 'low_bit':   9, 'readonly': False, 'desc': 'Enable supervisor-mode external interrupts' },
               'UEIE'  : { 'high_bit':  8, 'low_bit':   8, 'readonly': False, 'desc': 'Enable user-mode external interrupts' },
               'MTIE'  : { 'high_bit':  7, 'low_bit':   7, 'readonly': False, 'desc': 'Enable machine-mode timer interrupts' },
               'VSTIE' : { 'high_bit':  6, 'low_bit':   6, 'readonly': False, 'desc': 'Enable virtuall supervisor-mode timer interrupts' },
               'STIE'  : { 'high_bit':  5, 'low_bit':   5, 'readonly': False, 'desc': 'Enable supervisor-mode timer interrupts' },
               'UTIE'  : { 'high_bit':  4, 'low_bit':   4, 'readonly': False, 'desc': 'Enable user-mode timer interrupts' },
               'MSIE'  : { 'high_bit':  3, 'low_bit':   3, 'readonly': False, 'desc': 'Enable machine-mode software interrupts' },
               'VSSIE' : { 'high_bit':  2, 'low_bit':   2, 'readonly': False, 'desc': 'Enable virtual supervisor-mode software interrupts' },
               'SSIE'  : { 'high_bit':  1, 'low_bit':   1, 'readonly': False, 'desc': 'Enable supervisor-mode software interrupts' },
               'USIE'  : { 'high_bit':  0, 'low_bit':   0, 'readonly': False, 'desc': 'Enable user-mode software interrupts' },
             },
             'context': 'HART',
           },
    0x305: {
             'name': 'mtvec',
             'desc': 'Machine trap-handler base address.',
             'fields': {
               'BASE' : { 'high_bit': 31, 'low_bit':   2, 'readonly': False, 'desc': 'Vector base address' },
               'MODE' : { 'high_bit':  1, 'low_bit':   0, 'readonly': False , 'desc': '0 - Direct, 1 - Vectored' },
             },
             'context': 'HART',
           },
    0x306: {
             'name': 'mcounteren',
             'desc': 'Machine counter enable.',
             'fields': {
               'HPM31' : { 'high_bit': 31, 'low_bit':  31, 'readonly': False, 'desc': 'undocumented' },
               'HPM30' : { 'high_bit': 30, 'low_bit':  30, 'readonly': False, 'desc': 'undocumented' },
               'HPM29' : { 'high_bit': 29, 'low_bit':  29, 'readonly': False, 'desc': 'undocumented' },
               'HPM28' : { 'high_bit': 28, 'low_bit':  28, 'readonly': False, 'desc': 'undocumented' },
               'HPM27' : { 'high_bit': 27, 'low_bit':  27, 'readonly': False, 'desc': 'undocumented' },
               'HPM26' : { 'high_bit': 26, 'low_bit':  26, 'readonly': False, 'desc': 'undocumented' },
               'HPM25' : { 'high_bit': 25, 'low_bit':  25, 'readonly': False, 'desc': 'undocumented' },
               'HPM24' : { 'high_bit': 24, 'low_bit':  24, 'readonly': False, 'desc': 'undocumented' },
               'HPM23' : { 'high_bit': 23, 'low_bit':  23, 'readonly': False, 'desc': 'undocumented' },
               'HPM22' : { 'high_bit': 22, 'low_bit':  22, 'readonly': False, 'desc': 'undocumented' },
               'HPM21' : { 'high_bit': 21, 'low_bit':  21, 'readonly': False, 'desc': 'undocumented' },
               'HPM20' : { 'high_bit': 20, 'low_bit':  20, 'readonly': False, 'desc': 'undocumented' },
               'HPM19' : { 'high_bit': 19, 'low_bit':  19, 'readonly': False, 'desc': 'undocumented' },
               'HPM18' : { 'high_bit': 18, 'low_bit':  18, 'readonly': False, 'desc': 'undocumented' },
               'HPM17' : { 'high_bit': 17, 'low_bit':  17, 'readonly': False, 'desc': 'undocumented' },
               'HPM16' : { 'high_bit': 16, 'low_bit':  16, 'readonly': False, 'desc': 'undocumented' },
               'HPM15' : { 'high_bit': 15, 'low_bit':  15, 'readonly': False, 'desc': 'undocumented' },
               'HPM14' : { 'high_bit': 14, 'low_bit':  14, 'readonly': False, 'desc': 'undocumented' },
               'HPM13' : { 'high_bit': 13, 'low_bit':  13, 'readonly': False, 'desc': 'undocumented' },
               'HPM12' : { 'high_bit': 12, 'low_bit':  12, 'readonly': False, 'desc': 'undocumented' },
               'HPM11' : { 'high_bit': 11, 'low_bit':  11, 'readonly': False, 'desc': 'undocumented' },
               'HPM10' : { 'high_bit': 10, 'low_bit':  10, 'readonly': False, 'desc': 'undocumented' },
               'HPM9'  : { 'high_bit':  9, 'low_bit':   9, 'readonly': False, 'desc': 'undocumented' },
               'HPM8'  : { 'high_bit':  8, 'low_bit':   8, 'readonly': False, 'desc': 'undocumented' },
               'HPM7'  : { 'high_bit':  7, 'low_bit':   7, 'readonly': False, 'desc': 'undocumented' },
               'HPM6'  : { 'high_bit':  6, 'low_bit':   6, 'readonly': False, 'desc': 'undocumented' },
               'HPM5'  : { 'high_bit':  5, 'low_bit':   5, 'readonly': False, 'desc': 'undocumented' },
               'HPM4'  : { 'high_bit':  4, 'low_bit':   4, 'readonly': False, 'desc': 'undocumented' },
               'HPM3'  : { 'high_bit':  3, 'low_bit':   3, 'readonly': False, 'desc': 'undocumented' },
               'IR'    : { 'high_bit':  2, 'low_bit':   2, 'readonly': False, 'desc': 'undocumented' },
               'TM'    : { 'high_bit':  1, 'low_bit':   1, 'readonly': False, 'desc': 'undocumented' },
               'CY'    : { 'high_bit':  0, 'low_bit':   0, 'readonly': False, 'desc': 'undocumented' },
             },
             'context': 'HART',
           },
    0x310: {
             'name': 'mstatush',
             'desc': 'Additional machine status register, RV32 only',
             'fields': {
               'WPRI' : { 'high_bit':  3, 'low_bit':   0, 'readonly': True , 'desc': 'reserved' },
               'MPV'  : { 'high_bit':  7, 'low_bit':   7, 'readonly': False, 'desc': 'Machine previous virtualization mode' },
               'GVA'  : { 'high_bit':  6, 'low_bit':   6, 'readonly': False, 'desc': 'Guest virtual address' },
               'MBE'  : { 'high_bit':  5, 'low_bit':   5, 'readonly': False, 'desc': 'Controls endianness of explicit memory accesses made from M-mode' },
               'SBE'  : { 'high_bit':  4, 'low_bit':   4, 'readonly': False, 'desc': 'Controls endianness of explicit memory accesses made from S-mode' },
             },
             'context': 'HART',
           },

    # Machine Trap Handling
    0x340: {
             'name': 'mscratch',
             'desc': 'Scratch register for machine trap handlers.',
             'fields': {},
             'context': 'HART',
           },
    0x341: {
             'name': 'mepc',
             'desc': 'Machine exception program counter.',
             'fields': {},
             'context': 'HART',
           },
    0x342: {
             'name': 'mcause',
             'desc': 'Machine trap cause.',
             'fields': {
               'Interrupt' : { 'high_bit': 31, 'low_bit':  31, 'readonly': False, 'desc': 'Bit to set a trap' },
               'Code'      : { 'high_bit': 30, 'low_bit':   0, 'readonly': False, 'desc': 'The exception code' },
             },
             'context': 'HART',
           },
    0x343: {
             'name': 'mtval',
             'desc': 'Machine bad address or instruction.',
             'fields': {},
             'context': 'HART',
           },
    0x344: {
             'name': 'mip',
             'desc': 'Machine interrupt pending.',
             'fields': {
               'WPRI'  : { 'high_bit': 31, 'low_bit':  13, 'readonly': True , 'desc': 'undocumented' },
               'SGEIP' : { 'high_bit': 12, 'low_bit':  12, 'readonly': False, 'desc': 'Supervisor guest external interrupt pending' },
               'MEIP'  : { 'high_bit': 11, 'low_bit':  11, 'readonly': False, 'desc': 'Machine-mode external interrupt pending' },
               'VSEIP' : { 'high_bit': 10, 'low_bit':  10, 'readonly': False, 'desc': 'Virtual supervisor-mode external interrupt pending' },
               'SEIP'  : { 'high_bit':  9, 'low_bit':   9, 'readonly': False, 'desc': 'Supervisor-mode external interrupt pending' },
               'UEIP'  : { 'high_bit':  8, 'low_bit':   8, 'readonly': False, 'desc': 'User-mode external interrupts pending' },
               'MTIP'  : { 'high_bit':  7, 'low_bit':   7, 'readonly': False, 'desc': 'Machine-mode timer interrupt pending' },
               'VSTIP' : { 'high_bit':  6, 'low_bit':   6, 'readonly': False, 'desc': 'Virtual supervisor-mode timer interrupt pending' },
               'STIP'  : { 'high_bit':  5, 'low_bit':   5, 'readonly': False, 'desc': 'Supervisor-mode timer interrupt pending' },
               'UTIP'  : { 'high_bit':  4, 'low_bit':   4, 'readonly': False, 'desc': 'User-mode Machine timer interrupt pending' },
               'MSIP'  : { 'high_bit':  3, 'low_bit':   3, 'readonly': False, 'desc': 'Machine-mode software interrupt pending' },
               'VSSIP' : { 'high_bit':  2, 'low_bit':   2, 'readonly': False, 'desc': 'Virtual supervisor-mode software interrupt pending' },
               'SSIP'  : { 'high_bit':  1, 'low_bit':   1, 'readonly': False, 'desc': 'Supervisor-mode software interrupt pending' },
               'USIP'  : { 'high_bit':  0, 'low_bit':   0, 'readonly': False, 'desc': 'User-mode software interrupt pending' },
             },
             'context': 'HART',
           },

    0x34a: {
             'name': 'mtinst',
             'desc': 'Machine trap instruction (transformed).',
             'fields': {},
             'context': 'HART',
           },
    0x34b: {
             'name': 'mtval2',
             'desc': 'Machine bad guest physical address.',
             'fields': {},
             'context': 'HART',
           },

    # Smcsrind extension
    0x350: {
             'name': 'miselect',
             'desc': 'Machine Indirect Register Select',
             'fields': {},
             'extension': ['Smcsrind'],
             'context': 'HART',
           },
    0x351: {
             'name': 'mireg',
             'desc': 'Machine Indirect Register Alias',
             'fields': {},
             'extension': ['Smcsrind'],
             'context': 'HART',
           },
    0x352: {
             'name': 'mireg2',
             'desc': 'Machine Indirect Register Alias 2',
             'fields': {},
             'extension': ['Smcsrind'],
             'context': 'HART',
           },
    0x353: {
             'name': 'mireg3',
             'desc': 'Machine Indirect Register Alias 3',
             'fields': {},
             'extension': ['Smcsrind'],
             'context': 'HART',
           },
    0x354: {
             'name': 'mireg4',
             'desc': 'Machine Indirect Register Alias 4',
             'fields': {},
             'extension': ['Smcsrind'],
             'context': 'HART',
           },
    0x355: {
             'name': 'mireg5',
             'desc': 'Machine Indirect Register Alias 5',
             'fields': {},
             'extension': ['Smcsrind'],
             'context': 'HART',
           },
    0x356: {
             'name': 'mireg6',
             'desc': 'Machine Indirect Register Alias 6',
             'fields': {},
             'extension': ['Smcsrind'],
             'context': 'HART',
           },

    # Machine Configuration
    0x30a: {
             'name': 'menvcfg',
             'desc': 'Machine environment configuration register.',
             'fields': {
               'STCE'  : { 'high_bit': 31, 'low_bit':  31, 'readonly': False, 'desc': 'Supervisor Timer Interrupts enable' },
               'PBMTE' : { 'high_bit': 30, 'low_bit':  30, 'readonly': False, 'desc': 'Page-based memory type enable' },
               'ADUE'  : { 'high_bit': 29, 'low_bit':  29, 'readonly': False, 'desc': 'Update PTE A/D bits enable' },
               'CDE'   : { 'high_bit': 28, 'low_bit':  28, 'readonly': False, 'desc': '(Counter Delegation enable' },
               'DTE'   : { 'high_bit': 27, 'low_bit':  27, 'readonly': False, 'desc': 'Double trap enable' },
               'WPRI'  : { 'high_bit': 26, 'low_bit':   8, 'readonly': False, 'desc': 'reserved' },
               'CBZE'  : { 'high_bit':  7, 'low_bit':   7, 'readonly': False, 'desc': 'Cache block zero instruction enable' },
               'CBCFE' : { 'high_bit':  6, 'low_bit':   6, 'readonly': False, 'desc': 'Cache block clean and flush instruction enable' },
               'CBIE'  : { 'high_bit':  5, 'low_bit':   4, 'readonly': False, 'desc': 'Cache block invalidate instruction enable' },
               'FIOM'  : { 'high_bit':  0, 'low_bit':   0, 'readonly': False, 'desc': 'Fence of I/O implies Memory' },
             },
             'context': 'HART',
           },
    0x31a: {
             'name': 'menvcfgh',
             'desc': 'Additional machine environment configuration register, RV32 only.',
             'fields': {
               'WPRI' : { 'high_bit': 31, 'low_bit':   0, 'readonly': False, 'desc': 'reserved' },
             },
             'context': 'HART',
           },
    0x747: {
             'name': 'mseccfg',
             'desc': 'Machine security configuration register.',
             'fields': {
               'WPRI' : { 'high_bit': 31, 'low_bit':   0, 'readonly': False, 'desc': 'reserved' },
             },
             'context': 'HART',
           },
    0x757: {
             'name': 'mseccfgh',
             'desc': 'Additional machine security configuration register, RV32 only.',
             'fields': {
               'WPRI' : { 'high_bit': 31, 'low_bit':   0, 'readonly': False, 'desc': 'reserved' },
             },
             'context': 'HART',
           },

    # Machine Memory Protection
    0x3a0: {
             'name': 'pmpcfg0',
             'desc': 'Physical memory protection configuration.',
             'fields': {},
             'context': 'HART',
           },
    0x3a1: {
             'name': 'pmpcfg1',
             'desc': 'Physical memory protection configuration.',
             'fields': {},
             'context': 'HART',
           },
    0x3a2: {
             'name': 'pmpcfg2',
             'desc': 'Physical memory protection configuration.',
             'fields': {},
             'context': 'HART',
           },
    0x3a3: {
             'name': 'pmpcfg3',
             'desc': 'Physical memory protection configuration.',
             'fields': {},
             'context': 'HART',
           },
    0x3a4: {
             'name': 'pmpcfg4',
             'desc': 'Physical memory protection configuration.',
             'fields': {},
             'context': 'HART',
           },
    0x3a5: {
             'name': 'pmpcfg5',
             'desc': 'Physical memory protection configuration.',
             'fields': {},
             'context': 'HART',
           },
    0x3a6: {
             'name': 'pmpcfg6',
             'desc': 'Physical memory protection configuration.',
             'fields': {},
             'context': 'HART',
           },
    0x3a7: {
             'name': 'pmpcfg7',
             'desc': 'Physical memory protection configuration.',
             'fields': {},
             'context': 'HART',
           },
    0x3a8: {
             'name': 'pmpcfg8',
             'desc': 'Physical memory protection configuration.',
             'fields': {},
             'context': 'HART',
           },
    0x3a9: {
             'name': 'pmpcfg9',
             'desc': 'Physical memory protection configuration.',
             'fields': {},
             'context': 'HART',
           },
    0x3aa: {
             'name': 'pmpcfg10',
             'desc': 'Physical memory protection configuration.',
             'fields': {},
             'context': 'HART',
           },
    0x3ab: {
             'name': 'pmpcfg11',
             'desc': 'Physical memory protection configuration.',
             'fields': {},
             'context': 'HART',
           },
    0x3ac: {
             'name': 'pmpcfg12',
             'desc': 'Physical memory protection configuration.',
             'fields': {},
             'context': 'HART',
           },
    0x3ad: {
             'name': 'pmpcfg13',
             'desc': 'Physical memory protection configuration.',
             'fields': {},
             'context': 'HART',
           },
    0x3ae: {
             'name': 'pmpcfg14',
             'desc': 'Physical memory protection configuration.',
             'fields': {},
             'context': 'HART',
           },
    0x3af: {
             'name': 'pmpcfg15',
             'desc': 'Physical memory protection configuration.',
             'fields': {},
             'context': 'HART',
           },
    0x3b0: {
             'name': 'pmpaddr0',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3b1: {
             'name': 'pmpaddr1',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3b2: {
             'name': 'pmpaddr2',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3b3: {
             'name': 'pmpaddr3',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3b4: {
             'name': 'pmpaddr4',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3b5: {
             'name': 'pmpaddr5',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3b6: {
             'name': 'pmpaddr6',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3b7: {
             'name': 'pmpaddr7',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3b8: {
             'name': 'pmpaddr8',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3b9: {
             'name': 'pmpaddr9',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3ba: {
             'name': 'pmpaddr10',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3bb: {
             'name': 'pmpaddr11',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3bc: {
             'name': 'pmpaddr12',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3bd: {
             'name': 'pmpaddr13',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3be: {
             'name': 'pmpaddr14',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3bf: {
             'name': 'pmpaddr15',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3c0: {
             'name': 'pmpaddr16',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3c1: {
             'name': 'pmpaddr17',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3c2: {
             'name': 'pmpaddr18',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3c3: {
             'name': 'pmpaddr19',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3c4: {
             'name': 'pmpaddr20',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3c5: {
             'name': 'pmpaddr21',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3c6: {
             'name': 'pmpaddr22',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3c7: {
             'name': 'pmpaddr23',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3c8: {
             'name': 'pmpaddr24',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3c9: {
             'name': 'pmpaddr25',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3ca: {
             'name': 'pmpaddr26',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3cb: {
             'name': 'pmpaddr27',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3cc: {
             'name': 'pmpaddr28',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3cd: {
             'name': 'pmpaddr29',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3ce: {
             'name': 'pmpaddr30',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3cf: {
             'name': 'pmpaddr31',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3d0: {
             'name': 'pmpaddr32',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3d1: {
             'name': 'pmpaddr33',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3d2: {
             'name': 'pmpaddr34',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3d3: {
             'name': 'pmpaddr35',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3d4: {
             'name': 'pmpaddr36',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3d5: {
             'name': 'pmpaddr37',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3d6: {
             'name': 'pmpaddr38',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3d7: {
             'name': 'pmpaddr39',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3d8: {
             'name': 'pmpaddr40',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3d9: {
             'name': 'pmpaddr41',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3da: {
             'name': 'pmpaddr42',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3db: {
             'name': 'pmpaddr43',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3dc: {
             'name': 'pmpaddr44',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3dd: {
             'name': 'pmpaddr45',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3de: {
             'name': 'pmpaddr46',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3df: {
             'name': 'pmpaddr47',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3e0: {
             'name': 'pmpaddr48',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3e1: {
             'name': 'pmpaddr49',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3e2: {
             'name': 'pmpaddr50',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3e3: {
             'name': 'pmpaddr51',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3e4: {
             'name': 'pmpaddr52',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3e5: {
             'name': 'pmpaddr53',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3e6: {
             'name': 'pmpaddr54',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3e7: {
             'name': 'pmpaddr55',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3e8: {
             'name': 'pmpaddr56',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3e9: {
             'name': 'pmpaddr57',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3ea: {
             'name': 'pmpaddr58',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3eb: {
             'name': 'pmpaddr59',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3ec: {
             'name': 'pmpaddr60',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3ed: {
             'name': 'pmpaddr61',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3ee: {
             'name': 'pmpaddr62',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },
    0x3ef: {
             'name': 'pmpaddr63',
             'desc': 'Physical memory protection address register.',
             'fields': {},
             'context': 'HART',
           },

    # Smstateen: Machine state enable registers
    0x30c: {
             'name': 'mstateen0',
             'desc': 'Machine State Enable Register 0',
             'fields': {
               'WPRI' : { 'high_bit': 31, 'low_bit':   3, 'readonly': True , 'desc': 'Reserved' },
               'JVT'  : { 'high_bit':  2, 'low_bit':   2, 'readonly': False, 'desc': 'JVT register access' },
               'FCSR' : { 'high_bit':  1, 'low_bit':   1, 'readonly': False, 'desc': 'FCSR register access' },
               'C'    : { 'high_bit':  0, 'low_bit':   0, 'readonly': True , 'desc': 'Custom state access' },
             },
             'extension': ['Smstateen'],
             'context': 'HART',
           },
    0x30d: {
             'name': 'mstateen1',
             'desc': 'Machine State Enable Register 1',
             'fields': {},
             'extension': ['Smstateen'],
             'context': 'HART',
           },
    0x30e: {
             'name': 'mstateen2',
             'desc': 'Machine State Enable Register 2',
             'fields': {},
             'extension': ['Smstateen'],
             'context': 'HART',
           },
    0x30f: {
             'name': 'mstateen3',
             'desc': 'Machine State Enable Register 3',
             'fields': {},
             'extension': ['Smstateen'],
             'context': 'HART',
           },

    0x31c: {
             'name': 'mstateen0h',
             'desc': 'Machine State Enable Register 0, RV32 only',
             'fields': {
               'SE0'     : { 'high_bit': 31, 'low_bit':  31, 'readonly': False, 'desc': 'hstateen0/sstateen0 register access' },
               'ENVCFG'  : { 'high_bit': 30, 'low_bit':  30, 'readonly': False, 'desc': 'henvcfg/senvcfg register access' },
               'WPRI'    : { 'high_bit': 20, 'low_bit':   0, 'readonly': True , 'desc': 'Reserved' },
               'CSRIND'  : { 'high_bit': 28, 'low_bit':  28, 'readonly': False, 'desc': 'Sscsrind access' },
               'AIA'     : { 'high_bit': 27, 'low_bit':  27, 'readonly': False, 'desc': 'Ssaia state access' },
               'IMSIC'   : { 'high_bit': 26, 'low_bit':  26, 'readonly': False, 'desc': 'IMSIC state access' },
               'CONTEXT' : { 'high_bit': 25, 'low_bit':  25, 'readonly': False, 'desc': 'hcontext/scontext register access' },
               'P1P13'   : { 'high_bit': 24, 'low_bit':  24, 'readonly': False, 'desc': 'hedelegh register access' },
               'P1P14'   : { 'high_bit': 23, 'low_bit':  23, 'readonly': False, 'desc': 'srmcfg register access' },
               'CTR'     : { 'high_bit': 22, 'low_bit':  22, 'readonly': False, 'desc': 'CTR register access' },
               'CLIC'    : { 'high_bit': 21, 'low_bit':  21, 'readonly': False, 'desc': 'CLIC registers access' },
             },
             'extension': ['Smstateen'],
             'context': 'HART',
           },
    0x31d: {
             'name': 'mstateen1h',
             'desc': 'Machine State Enable Register 1, RV32 only',
             'fields': {},
             'extension': ['Smstateen'],
             'context': 'HART',
           },
    0x31e: {
             'name': 'mstateen2h',
             'desc': 'Machine State Enable Register 2, RV32 only',
             'fields': {},
             'extension': ['Smstateen'],
             'context': 'HART',
           },
    0x31f: {
             'name': 'mstateen3h',
             'desc': 'Machine State Enable Register 3, RV32 only',
             'fields': {},
             'extension': ['Smstateen'],
             'context': 'HART',
           },

    # Machine Counter/Timers
    0xB00: {
             'name': 'mcycle',
             'desc': 'Machine cycle counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB02: {
             'name': 'minstret',
             'desc': 'Machine instructions-retired counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB03: {
             'name': 'mhpmcounter3',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB04: {
             'name': 'mhpmcounter4',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB05: {
             'name': 'mhpmcounter5',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB06: {
             'name': 'mhpmcounter6',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB07: {
             'name': 'mhpmcounter7',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB08: {
             'name': 'mhpmcounter8',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB09: {
             'name': 'mhpmcounter9',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB0A: {
             'name': 'mhpmcounter10',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB0B: {
             'name': 'mhpmcounter11',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB0C: {
             'name': 'mhpmcounter12',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB0D: {
             'name': 'mhpmcounter13',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB0E: {
             'name': 'mhpmcounter14',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB0F: {
             'name': 'mhpmcounter15',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB10: {
             'name': 'mhpmcounter16',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB11: {
             'name': 'mhpmcounter17',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB12: {
             'name': 'mhpmcounter18',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB13: {
             'name': 'mhpmcounter19',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB14: {
             'name': 'mhpmcounter20',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB15: {
             'name': 'mhpmcounter21',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB16: {
             'name': 'mhpmcounter22',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB17: {
             'name': 'mhpmcounter23',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB18: {
             'name': 'mhpmcounter24',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB19: {
             'name': 'mhpmcounter25',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB1A: {
             'name': 'mhpmcounter26',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB1B: {
             'name': 'mhpmcounter27',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB1C: {
             'name': 'mhpmcounter28',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB1D: {
             'name': 'mhpmcounter29',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB1E: {
             'name': 'mhpmcounter30',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },
    0xB1F: {
             'name': 'mhpmcounter31',
             'desc': 'Machine performance-monitoring counter.',
             'fields': {},
             'context': 'HART',
           },

    # Machine Counter Setup
    0x320: {
             'name': 'mcountinhibit',
             'desc': 'Machine counter-inhibit register.',
             'fields': {
               'HPM31' : { 'high_bit': 31, 'low_bit':  31, 'readonly': False, 'desc': 'undocumented' },
               'HPM30' : { 'high_bit': 30, 'low_bit':  30, 'readonly': False, 'desc': 'undocumented' },
               'HPM29' : { 'high_bit': 29, 'low_bit':  29, 'readonly': False, 'desc': 'undocumented' },
               'HPM28' : { 'high_bit': 28, 'low_bit':  28, 'readonly': False, 'desc': 'undocumented' },
               'HPM27' : { 'high_bit': 27, 'low_bit':  27, 'readonly': False, 'desc': 'undocumented' },
               'HPM26' : { 'high_bit': 26, 'low_bit':  26, 'readonly': False, 'desc': 'undocumented' },
               'HPM25' : { 'high_bit': 25, 'low_bit':  25, 'readonly': False, 'desc': 'undocumented' },
               'HPM24' : { 'high_bit': 24, 'low_bit':  24, 'readonly': False, 'desc': 'undocumented' },
               'HPM23' : { 'high_bit': 23, 'low_bit':  23, 'readonly': False, 'desc': 'undocumented' },
               'HPM22' : { 'high_bit': 22, 'low_bit':  22, 'readonly': False, 'desc': 'undocumented' },
               'HPM21' : { 'high_bit': 21, 'low_bit':  21, 'readonly': False, 'desc': 'undocumented' },
               'HPM20' : { 'high_bit': 20, 'low_bit':  20, 'readonly': False, 'desc': 'undocumented' },
               'HPM19' : { 'high_bit': 19, 'low_bit':  19, 'readonly': False, 'desc': 'undocumented' },
               'HPM18' : { 'high_bit': 18, 'low_bit':  18, 'readonly': False, 'desc': 'undocumented' },
               'HPM17' : { 'high_bit': 17, 'low_bit':  17, 'readonly': False, 'desc': 'undocumented' },
               'HPM16' : { 'high_bit': 16, 'low_bit':  16, 'readonly': False, 'desc': 'undocumented' },
               'HPM15' : { 'high_bit': 15, 'low_bit':  15, 'readonly': False, 'desc': 'undocumented' },
               'HPM14' : { 'high_bit': 14, 'low_bit':  14, 'readonly': False, 'desc': 'undocumented' },
               'HPM13' : { 'high_bit': 13, 'low_bit':  13, 'readonly': False, 'desc': 'undocumented' },
               'HPM12' : { 'high_bit': 12, 'low_bit':  12, 'readonly': False, 'desc': 'undocumented' },
               'HPM11' : { 'high_bit': 11, 'low_bit':  11, 'readonly': False, 'desc': 'undocumented' },
               'HPM10' : { 'high_bit': 10, 'low_bit':  10, 'readonly': False, 'desc': 'undocumented' },
               'HPM9'  : { 'high_bit':  9, 'low_bit':   9, 'readonly': False, 'desc': 'undocumented' },
               'HPM8'  : { 'high_bit':  8, 'low_bit':   8, 'readonly': False, 'desc': 'undocumented' },
               'HPM7'  : { 'high_bit':  7, 'low_bit':   7, 'readonly': False, 'desc': 'undocumented' },
               'HPM6'  : { 'high_bit':  6, 'low_bit':   6, 'readonly': False, 'desc': 'undocumented' },
               'HPM5'  : { 'high_bit':  5, 'low_bit':   5, 'readonly': False, 'desc': 'undocumented' },
               'HPM4'  : { 'high_bit':  4, 'low_bit':   4, 'readonly': False, 'desc': 'undocumented' },
               'HPM3'  : { 'high_bit':  3, 'low_bit':   3, 'readonly': False, 'desc': 'undocumented' },
               'IR'    : { 'high_bit':  2, 'low_bit':   2, 'readonly': False, 'desc': 'undocumented' },
               'RESV'  : { 'high_bit':  1, 'low_bit':   1, 'readonly': True , 'desc': 'undocumented' },
               'CY'    : { 'high_bit':  0, 'low_bit':   0, 'readonly': False, 'desc': 'undocumented' },
             },
             'context': 'HART',
           },
    0x323: {
             'name': 'mhpmevent3',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x324: {
             'name': 'mhpmevent4',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x325: {
             'name': 'mhpmevent5',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x326: {
             'name': 'mhpmevent6',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x327: {
             'name': 'mhpmevent7',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x328: {
             'name': 'mhpmevent8',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x329: {
             'name': 'mhpmevent9',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x32A: {
             'name': 'mhpmevent10',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x32B: {
             'name': 'mhpmevent11',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x32C: {
             'name': 'mhpmevent12',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x32D: {
             'name': 'mhpmevent13',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x32E: {
             'name': 'mhpmevent14',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x32F: {
             'name': 'mhpmevent15',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x330: {
             'name': 'mhpmevent16',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x331: {
             'name': 'mhpmevent17',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x332: {
             'name': 'mhpmevent18',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x333: {
             'name': 'mhpmevent19',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x334: {
             'name': 'mhpmevent20',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x335: {
             'name': 'mhpmevent21',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x336: {
             'name': 'mhpmevent22',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x337: {
             'name': 'mhpmevent23',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x338: {
             'name': 'mhpmevent24',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x339: {
             'name': 'mhpmevent25',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x33A: {
             'name': 'mhpmevent26',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x33B: {
             'name': 'mhpmevent27',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x33C: {
             'name': 'mhpmevent28',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x33D: {
             'name': 'mhpmevent29',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x33E: {
             'name': 'mhpmevent30',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },
    0x33F: {
             'name': 'mhpmevent31',
             'desc': 'Machine performance-monitoring event selector.',
             'fields': {},
             'context': 'HART',
           },

    # Debug/Trace Registers (shared with Debug Mode)
    0x7a0: {
             'name': 'tselect',
             'desc': 'Debug/Trace trigger register select.',
             'fields': {},
             'context': 'HART',
           },
    0x7a1: {
             'name': 'tdata1',
             'desc': 'First Debug/Trace trigger data register.',
             'fields': {
               'type'             : { 'high_bit': 31, 'low_bit':  28, 'readonly': False, 'desc': 'Type of trigger' },
               'dmode'            : { 'high_bit': 27, 'low_bit':  27, 'readonly': False, 'desc': 'If bit is set, only Debug Mode can write to the tdata registers. Other writes are ignored.' },
               'data'             : { 'high_bit': 26, 'low_bit':   0, 'readonly': False, 'desc': 'Trigger-specific data' },
               'mcontrol_maskmax' : { 'high_bit': 26, 'low_bit':  23, 'readonly': False, 'desc': 'FIXME: Debug spec has a bug, not enough bits for RV32' },
               'mcontrol_sizehi'  : { 'high_bit': 22, 'low_bit':  21, 'readonly': False, 'desc': 'TODO' },
               'mcontrol_hit'     : { 'high_bit': 20, 'low_bit':  20, 'readonly': False, 'desc': 'Set when this trigger matches (optional)' },
               'mcontrol_select'  : { 'high_bit': 19, 'low_bit':  19, 'readonly': False, 'desc': 'TODO' },
               'mcontrol_timing'  : { 'high_bit': 18, 'low_bit':  18, 'readonly': False, 'desc': 'TODO' },
               'mcontrol_sizelo'  : { 'high_bit': 17, 'low_bit':  16, 'readonly': False, 'desc': 'TODO' },
               'mcontrol_action'  : { 'high_bit': 15, 'low_bit':  12, 'readonly': False, 'desc': 'Action to take when trigger is fired' },
               'mcontrol_chain'   : { 'high_bit': 11, 'low_bit':  11, 'readonly': False, 'desc': 'TODO' },
               'mcontrol_match'   : { 'high_bit': 10, 'low_bit':   7, 'readonly': False, 'desc': 'TODO' },
               'mcontrol_m'       : { 'high_bit':  6, 'low_bit':   6, 'readonly': False, 'desc': 'Enables this trigger in M-mode' },
               'mcontrol_s'       : { 'high_bit':  4, 'low_bit':   4, 'readonly': False, 'desc': 'Enables this trigger in S-mode' },
               'mcontrol_u'       : { 'high_bit':  3, 'low_bit':   3, 'readonly': False, 'desc': 'Enables this trigger in U-mode' },
               'mcontrol_execute' : { 'high_bit':  2, 'low_bit':   2, 'readonly': False, 'desc': 'When set, trigger fires on VA or opcode of instructions' },
               'mcontrol_store'   : { 'high_bit':  1, 'low_bit':   1, 'readonly': False, 'desc': 'When set, trigger fires on VA or data of stores' },
               'mcontrol_load'    : { 'high_bit':  0, 'low_bit':   0, 'readonly': False, 'desc': 'When set, trigger fires on VA or data of loads' },
               'icount_hit'       : { 'high_bit': 24, 'low_bit':  24, 'readonly': False, 'desc': 'Set when this trigger matches (optional)' },
               'icount_count'     : { 'high_bit': 23, 'low_bit':  10, 'readonly': False, 'desc': 'When count is decremented to 0, this trigger fires' },
               'icount_m'         : { 'high_bit':  9, 'low_bit':   9, 'readonly': False, 'desc': 'Decrement count in M-mode' },
               'icount_s'         : { 'high_bit':  7, 'low_bit':   7, 'readonly': False, 'desc': 'Decrement count in S-mode' },
               'icount_u'         : { 'high_bit':  6, 'low_bit':   6, 'readonly': False, 'desc': 'Decrement count in U-mode' },
               'icount_action'    : { 'high_bit':  5, 'low_bit':   0, 'readonly': False, 'desc': 'Action to take when trigger is fired' },
               'etrigger_hit'     : { 'high_bit': 26, 'low_bit':  26, 'readonly': False, 'desc': 'Set when this trigger matches (optional)' },
               'etrigger_m'       : { 'high_bit':  9, 'low_bit':   9, 'readonly': False, 'desc': 'Enables this trigger in M-mode' },
               'etrigger_s'       : { 'high_bit':  7, 'low_bit':   7, 'readonly': False, 'desc': 'Enables this trigger in S-mode' },
               'etrigger_u'       : { 'high_bit':  6, 'low_bit':   6, 'readonly': False, 'desc': 'Enables this trigger in U-mode' },
               'etrigger_action'  : { 'high_bit':  5, 'low_bit':   0, 'readonly': False, 'desc': 'Action to take when trigger is fired' },
               'itrigger_hit'     : { 'high_bit': 26, 'low_bit':  26, 'readonly': False, 'desc': 'Set when this trigger matches (optional)' },
               'itrigger_m'       : { 'high_bit':  9, 'low_bit':   9, 'readonly': False, 'desc': 'Enables this trigger in M-mode' },
               'itrigger_s'       : { 'high_bit':  7, 'low_bit':   7, 'readonly': False, 'desc': 'Enables this trigger in S-mode' },
               'itrigger_u'       : { 'high_bit':  6, 'low_bit':   6, 'readonly': False, 'desc': 'Enables this trigger in U-mode' },
               'itrigger_action'  : { 'high_bit':  5, 'low_bit':   0, 'readonly': False, 'desc': 'Action to take when trigger is fired' },
             },
             'context': 'HART',
           },
    0x7a2: {
             'name': 'tdata2',
             'desc': 'Second Debug/Trace trigger data register.',
             'fields': {},
             'context': 'HART',
           },
    0x7a3: {
             'name': 'tdata3',
             'desc': 'Third Debug/Trace trigger data register.',
             'fields': {},
             'context': 'HART',
           },
    0x7a4: {
             'name': 'tinfo',
             'desc': 'Trigger info',
             'fields': {},
             'context': 'HART',
           },
    0x7a5: {
             'name': 'tcontrol',
             'desc': 'Trigger control',
             'fields': {
               'Resv' : { 'high_bit':  2, 'low_bit':   0, 'readonly': True , 'desc': 'Tied to zero' },
               'mpte' : { 'high_bit':  7, 'low_bit':   7, 'readonly': False, 'desc': 'M-mode previous trigger enable field' },
               'mte'  : { 'high_bit':  3, 'low_bit':   3, 'readonly': False, 'desc': 'M-mode trigger enable field' },
             },
             'context': 'HART',
           },
    0x7a8: {
             'name': 'mcontext',
             'desc': 'Machine context',
             'fields': {},
             'context': 'HART',
           },
    0x7aa: {
             'name': 'scontext',
             'desc': 'Supervisor context',
             'fields': {},
             'context': 'HART',
           },

    #Debug Mode Registers
    0x7b0: {
             'name': 'dcsr',
             'desc': 'Debug control and status register.',
             'fields': {
               'xdebugver' : { 'high_bit': 31, 'low_bit':  28, 'readonly': True , 'desc': 'External debug support available' },
               'RESV'      : { 'high_bit':  5, 'low_bit':   5, 'readonly': False, 'desc': 'undocumented' },
               'ebreakm'   : { 'high_bit': 15, 'low_bit':  15, 'readonly': False, 'desc': 'If set, M-mode ebreak instructions will enter debug mode' },
               'ebreaks'   : { 'high_bit': 13, 'low_bit':  13, 'readonly': False, 'desc': 'If set, S-mode ebreak instructions will enter debug mode' },
               'ebreaku'   : { 'high_bit': 12, 'low_bit':  12, 'readonly': False, 'desc': 'If set, U-mode ebreak instructions will enter debug mode' },
               'stepie'    : { 'high_bit': 11, 'low_bit':  11, 'readonly': False, 'desc': 'Enables interrupts during single-stepping' },
               'stopcount' : { 'high_bit': 10, 'low_bit':  10, 'readonly': False, 'desc': "If set, don't increment any counters while in debug mode" },
               'stoptime'  : { 'high_bit':  9, 'low_bit':   9, 'readonly': False, 'desc': "If set, don't increment any timers while in debug mode" },
               'cause'     : { 'high_bit':  8, 'low_bit':   6, 'readonly': False, 'desc': 'Explains why debug mode was entered' },
               'mprven'    : { 'high_bit':  4, 'low_bit':   4, 'readonly': False, 'desc': 'If not set, ignore mstatus.mprv when in debug mode' },
               'nmip'      : { 'high_bit':  3, 'low_bit':   3, 'readonly': False, 'desc': 'When set, there is a non-maskable interrupt pending' },
               'step'      : { 'high_bit':  2, 'low_bit':   2, 'readonly': False, 'desc': 'When set and not in debug mode, execute a single execute then enter debug mode' },
               'prv'       : { 'high_bit':  1, 'low_bit':   0, 'readonly': True , 'desc': 'Previous privilege mode when entering debug mode' },
             },
             'context': 'HART',
           },
    0x7b1: {
             'name': 'dpc',
             'desc': 'Debug PC',
             'fields': {},
             'context': 'HART',
           },
    0x7b2: {
             'name': 'dscratch0',
             'desc': 'Debug scratch register 0.',
             'fields': {},
             'context': 'HART',
           },
    0x7b3: {
             'name': 'dscratch1',
             'desc': 'Debug scratch register 1.',
             'fields': {},
             'context': 'HART',
           },
}
