on:
  pull_request:
    branches:
      - main

env:
  CACHE_VERSION: v1

name: Regress Pegasus on Ubuntu
jobs:
  build_test_job:
    strategy:
      # Strategy is a matrix of debug and release builds/regression
      matrix:
        os: [ubuntu-24.04]
        BUILD_TYPE: [Debug,Release]
        COMPILER: [gcc,clang]

    name: Ubuntu-${{ matrix.BUILD_TYPE }}-${{matrix.COMPILER}}
    runs-on: ${{ matrix.os }}

    # Set up a global environment variable for build scripts
    env:
      PEGASUS_BUILD_TYPE: ${{ matrix.BUILD_TYPE }}
      COMPILER:           ${{ matrix.COMPILER }}

    steps:
      # Get Pegasus
      - name: Clone Pegasus
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Get Sparta
      - name: Checkout Sparta
        uses: actions/checkout@v4
        with:
          repository: sparcians/map
          submodules: recursive
          path: map
          ref: map_v2.1.1

      # Setup CCache to cache builds
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.os }}-${{ matrix.BUILD_TYPE }}-${{ matrix.COMPILER }}-ccache-${{ github.ref_name }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.BUILD_TYPE }}-${{ matrix.COMPILER }}-ccache-main
            ${{ matrix.os }}-${{ matrix.BUILD_TYPE }}-${{ matrix.COMPILER }}-ccache

      # Install missing packages to make everything build
      - name: Install packages needed for sparta/pegasus
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install libboost-all-dev libyaml-cpp-dev rapidjson-dev libhdf5-dev llvm

      # Build
      - name: Build
        run: ./.github/actions/build.sh

      # Regress
      - name: Regress
        run: ./.github/actions/regress.sh

      # Save error logs, etc
      - name: Save artifacts
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ErrorLogs-${{matrix.BUILD_TYPE}}-${{matrix.COMPILER}}
          path: ${{matrix.BUILD_TYPE}}/

      #- name: CTest
      #  # Run CTests without Valgrind tests otherwise the runtime will be TOO long
      #  if: ${{ env.DABBLE_BUILD_TYPE == 'release' }} && ${{ env.VALGRIND == 'false' }}
      #  uses: ./.github/actions/ctest  # Uses an action.yml in directory
